/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using TemplateFox.SDK.Client;
using TemplateFox.SDK.Api;
// uncomment below to import models
//using TemplateFox.SDK.Model;

namespace TemplateFox.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing AgentApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AgentApiTests : IDisposable
    {
        private AgentApi instance;

        public AgentApiTests()
        {
            instance = new AgentApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AgentApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AgentApi
            //Assert.IsType<AgentApi>(instance);
        }

        /// <summary>
        /// Test CreateAgentTemplate
        /// </summary>
        [Fact]
        public void CreateAgentTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateAgentTemplateRequest createAgentTemplateRequest = null;
            //var response = instance.CreateAgentTemplate(createAgentTemplateRequest);
            //Assert.IsType<AgentJobCreatedResponse>(response);
        }

        /// <summary>
        /// Test GetAgentJob
        /// </summary>
        [Fact]
        public void GetAgentJobTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string jobId = null;
            //var response = instance.GetAgentJob(jobId);
            //Assert.IsType<AgentJobStatusResponse>(response);
        }

        /// <summary>
        /// Test ReviseAgentTemplate
        /// </summary>
        [Fact]
        public void ReviseAgentTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string templateId = null;
            //ReviseAgentTemplateRequest reviseAgentTemplateRequest = null;
            //var response = instance.ReviseAgentTemplate(templateId, reviseAgentTemplateRequest);
            //Assert.IsType<AgentJobCreatedResponse>(response);
        }
    }
}
