/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.11.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using TemplateFox.SDK.Client;
using TemplateFox.SDK.Api;
// uncomment below to import models
//using TemplateFox.SDK.Model;

namespace TemplateFox.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing ImageApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ImageApiTests : IDisposable
    {
        private ImageApi instance;

        public ImageApiTests()
        {
            instance = new ImageApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImageApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ImageApi
            //Assert.IsType<ImageApi>(instance);
        }

        /// <summary>
        /// Test CreateImage
        /// </summary>
        [Fact]
        public void CreateImageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateImageRequest createImageRequest = null;
            //var response = instance.CreateImage(createImageRequest);
            //Assert.IsType<CreateImageResponse>(response);
        }
    }
}
