/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using TemplateFox.SDK.Client;
using TemplateFox.SDK.Api;
// uncomment below to import models
//using TemplateFox.SDK.Model;

namespace TemplateFox.SDK.Test.Api
{
    /// <summary>
    ///  Class for testing PDFToolsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PDFToolsApiTests : IDisposable
    {
        private PDFToolsApi instance;

        public PDFToolsApiTests()
        {
            instance = new PDFToolsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PDFToolsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PDFToolsApi
            //Assert.IsType<PDFToolsApi>(instance);
        }

        /// <summary>
        /// Test ExtractPdfPages
        /// </summary>
        [Fact]
        public void ExtractPdfPagesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ExtractPdfPagesRequest extractPdfPagesRequest = null;
            //var response = instance.ExtractPdfPages(extractPdfPagesRequest);
            //Assert.IsType<PdfToolsResponse>(response);
        }

        /// <summary>
        /// Test MergePdf
        /// </summary>
        [Fact]
        public void MergePdfTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MergePdfRequest mergePdfRequest = null;
            //var response = instance.MergePdf(mergePdfRequest);
            //Assert.IsType<PdfToolsResponse>(response);
        }

        /// <summary>
        /// Test RotatePdf
        /// </summary>
        [Fact]
        public void RotatePdfTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RotatePdfRequest rotatePdfRequest = null;
            //var response = instance.RotatePdf(rotatePdfRequest);
            //Assert.IsType<PdfToolsResponse>(response);
        }
    }
}
