/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// AgentJobStatusResponse
    /// </summary>
    [DataContract(Name = "AgentJobStatusResponse")]
    public partial class AgentJobStatusResponse : IValidatableObject
    {
        /// <summary>
        /// Defines Kind
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum KindEnum
        {
            /// <summary>
            /// Enum Create for value: create
            /// </summary>
            [EnumMember(Value = "create")]
            Create = 1,

            /// <summary>
            /// Enum Revise for value: revise
            /// </summary>
            [EnumMember(Value = "revise")]
            Revise = 2
        }


        /// <summary>
        /// Gets or Sets Kind
        /// </summary>
        [DataMember(Name = "kind", IsRequired = true, EmitDefaultValue = true)]
        public KindEnum Kind { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public AppRoutersV1AgentJobStatus Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentJobStatusResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AgentJobStatusResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentJobStatusResponse" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="kind">kind (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="templateId">templateId.</param>
        /// <param name="previewUrl">previewUrl.</param>
        /// <param name="previewExpiresAt">previewExpiresAt.</param>
        /// <param name="notes">notes.</param>
        /// <param name="creditsCharged">creditsCharged (required).</param>
        /// <param name="errorMessage">errorMessage.</param>
        /// <param name="errorCode">errorCode.</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        /// <param name="completedAt">completedAt.</param>
        public AgentJobStatusResponse(string id = default, KindEnum kind = default, AppRoutersV1AgentJobStatus status = default, string templateId = default, string previewUrl = default, string previewExpiresAt = default, string notes = default, int creditsCharged = default, string errorMessage = default, string errorCode = default, string createdAt = default, string updatedAt = default, string completedAt = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for AgentJobStatusResponse and cannot be null");
            }
            this.Id = id;
            this.Kind = kind;
            this.Status = status;
            this.CreditsCharged = creditsCharged;
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for AgentJobStatusResponse and cannot be null");
            }
            this.CreatedAt = createdAt;
            // to ensure "updatedAt" is required (not null)
            if (updatedAt == null)
            {
                throw new ArgumentNullException("updatedAt is a required property for AgentJobStatusResponse and cannot be null");
            }
            this.UpdatedAt = updatedAt;
            this.TemplateId = templateId;
            this.PreviewUrl = previewUrl;
            this.PreviewExpiresAt = previewExpiresAt;
            this.Notes = notes;
            this.ErrorMessage = errorMessage;
            this.ErrorCode = errorCode;
            this.CompletedAt = completedAt;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets TemplateId
        /// </summary>
        [DataMember(Name = "template_id", EmitDefaultValue = true)]
        public string TemplateId { get; set; }

        /// <summary>
        /// Gets or Sets PreviewUrl
        /// </summary>
        [DataMember(Name = "preview_url", EmitDefaultValue = true)]
        public string PreviewUrl { get; set; }

        /// <summary>
        /// Gets or Sets PreviewExpiresAt
        /// </summary>
        [DataMember(Name = "preview_expires_at", EmitDefaultValue = true)]
        public string PreviewExpiresAt { get; set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [DataMember(Name = "notes", EmitDefaultValue = true)]
        public string Notes { get; set; }

        /// <summary>
        /// Gets or Sets CreditsCharged
        /// </summary>
        [DataMember(Name = "credits_charged", IsRequired = true, EmitDefaultValue = true)]
        public int CreditsCharged { get; set; }

        /// <summary>
        /// Gets or Sets ErrorMessage
        /// </summary>
        [DataMember(Name = "error_message", EmitDefaultValue = true)]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>
        [DataMember(Name = "error_code", EmitDefaultValue = true)]
        public string ErrorCode { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updated_at", IsRequired = true, EmitDefaultValue = true)]
        public string UpdatedAt { get; set; }

        /// <summary>
        /// Gets or Sets CompletedAt
        /// </summary>
        [DataMember(Name = "completed_at", EmitDefaultValue = true)]
        public string CompletedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AgentJobStatusResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  PreviewUrl: ").Append(PreviewUrl).Append("\n");
            sb.Append("  PreviewExpiresAt: ").Append(PreviewExpiresAt).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  CreditsCharged: ").Append(CreditsCharged).Append("\n");
            sb.Append("  ErrorMessage: ").Append(ErrorMessage).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  CompletedAt: ").Append(CompletedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
