/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// AgentJobCreatedResponse
    /// </summary>
    [DataContract(Name = "AgentJobCreatedResponse")]
    public partial class AgentJobCreatedResponse : IValidatableObject
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pending for value: pending
            /// </summary>
            [EnumMember(Value = "pending")]
            Pending = 1
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentJobCreatedResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AgentJobCreatedResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AgentJobCreatedResponse" /> class.
        /// </summary>
        /// <param name="jobId">jobId (required).</param>
        /// <param name="status">status (required).</param>
        /// <param name="creditsCharged">creditsCharged (required).</param>
        /// <param name="creditsRemaining">creditsRemaining (required).</param>
        public AgentJobCreatedResponse(string jobId = default, StatusEnum status = default, int creditsCharged = default, int creditsRemaining = default)
        {
            // to ensure "jobId" is required (not null)
            if (jobId == null)
            {
                throw new ArgumentNullException("jobId is a required property for AgentJobCreatedResponse and cannot be null");
            }
            this.JobId = jobId;
            this.Status = status;
            this.CreditsCharged = creditsCharged;
            this.CreditsRemaining = creditsRemaining;
        }

        /// <summary>
        /// Gets or Sets JobId
        /// </summary>
        [DataMember(Name = "job_id", IsRequired = true, EmitDefaultValue = true)]
        public string JobId { get; set; }

        /// <summary>
        /// Gets or Sets CreditsCharged
        /// </summary>
        [DataMember(Name = "credits_charged", IsRequired = true, EmitDefaultValue = true)]
        public int CreditsCharged { get; set; }

        /// <summary>
        /// Gets or Sets CreditsRemaining
        /// </summary>
        [DataMember(Name = "credits_remaining", IsRequired = true, EmitDefaultValue = true)]
        public int CreditsRemaining { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AgentJobCreatedResponse {\n");
            sb.Append("  JobId: ").Append(JobId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreditsCharged: ").Append(CreditsCharged).Append("\n");
            sb.Append("  CreditsRemaining: ").Append(CreditsRemaining).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
