/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Optional brand constraints passed to the agent.
    /// </summary>
    [DataContract(Name = "BrandInputs")]
    public partial class BrandInputs : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BrandInputs" /> class.
        /// </summary>
        /// <param name="colors">Brand colors as hex strings, e.g. [&#39;#0C3C5F&#39;, &#39;#E27D28&#39;].</param>
        /// <param name="fonts">Preferred font families. Non-built-in fonts are substituted with the closest built-in and noted in the result..</param>
        /// <param name="assetUrls">Public https:// URLs of assets (logo, photos) the agent may use..</param>
        public BrandInputs(List<string> colors = default, List<string> fonts = default, List<string> assetUrls = default)
        {
            this.Colors = colors;
            this.Fonts = fonts;
            this.AssetUrls = assetUrls;
        }

        /// <summary>
        /// Brand colors as hex strings, e.g. [&#39;#0C3C5F&#39;, &#39;#E27D28&#39;]
        /// </summary>
        /// <value>Brand colors as hex strings, e.g. [&#39;#0C3C5F&#39;, &#39;#E27D28&#39;]</value>
        [DataMember(Name = "colors", EmitDefaultValue = false)]
        public List<string> Colors { get; set; }

        /// <summary>
        /// Preferred font families. Non-built-in fonts are substituted with the closest built-in and noted in the result.
        /// </summary>
        /// <value>Preferred font families. Non-built-in fonts are substituted with the closest built-in and noted in the result.</value>
        [DataMember(Name = "fonts", EmitDefaultValue = false)]
        public List<string> Fonts { get; set; }

        /// <summary>
        /// Public https:// URLs of assets (logo, photos) the agent may use.
        /// </summary>
        /// <value>Public https:// URLs of assets (logo, photos) the agent may use.</value>
        [DataMember(Name = "asset_urls", EmitDefaultValue = false)]
        public List<string> AssetUrls { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BrandInputs {\n");
            sb.Append("  Colors: ").Append(Colors).Append("\n");
            sb.Append("  Fonts: ").Append(Fonts).Append("\n");
            sb.Append("  AssetUrls: ").Append(AssetUrls).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
