/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Request model for image generation
    /// </summary>
    [DataContract(Name = "CreateImageRequest")]
    public partial class CreateImageRequest : IValidatableObject
    {

        /// <summary>
        /// Output image format: &#x60;png&#x60; (default), &#x60;jpeg&#x60; or &#x60;webp&#x60;.
        /// </summary>
        /// <value>Output image format: &#x60;png&#x60; (default), &#x60;jpeg&#x60; or &#x60;webp&#x60;.</value>
        [DataMember(Name = "format", EmitDefaultValue = false)]
        public ImageFormat? Format { get; set; }

        /// <summary>
        /// Export format: &#x60;url&#x60; uploads to CDN and returns URL, &#x60;binary&#x60; returns raw image bytes
        /// </summary>
        /// <value>Export format: &#x60;url&#x60; uploads to CDN and returns URL, &#x60;binary&#x60; returns raw image bytes</value>
        [DataMember(Name = "export_type", EmitDefaultValue = false)]
        public AppRoutersV1DeliveryExportType? ExportType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateImageRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateImageRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateImageRequest" /> class.
        /// </summary>
        /// <param name="templateId">Template short ID (12 characters) (required).</param>
        /// <param name="modifications">modifications.</param>
        /// <param name="data">Optional key-value data merged into &#x60;{{ }}&#x60; template variables. For most image templates, prefer &#x60;modifications&#x60; instead..</param>
        /// <param name="format">Output image format: &#x60;png&#x60; (default), &#x60;jpeg&#x60; or &#x60;webp&#x60;..</param>
        /// <param name="width">width.</param>
        /// <param name="quality">Compression quality for &#x60;jpeg&#x60;/&#x60;webp&#x60; (1-100). Ignored for &#x60;png&#x60;. (default to 85).</param>
        /// <param name="exportType">Export format: &#x60;url&#x60; uploads to CDN and returns URL, &#x60;binary&#x60; returns raw image bytes.</param>
        /// <param name="expiration">URL expiration in seconds. Min: 60 (1 min), Max: 604800 (7 days). Only applies to &#x60;url&#x60; export type. (default to 86400).</param>
        /// <param name="filename">filename.</param>
        /// <param name="storeS3">Upload to your configured S3 bucket instead of CDN (default to false).</param>
        /// <param name="s3Filepath">s3Filepath.</param>
        /// <param name="s3Bucket">s3Bucket.</param>
        /// <param name="varVersion">varVersion.</param>
        public CreateImageRequest(string templateId = default, List<Modification> modifications = default, Dictionary<string, Object> data = default, ImageFormat? format = default, int? width = default, int quality = 85, AppRoutersV1DeliveryExportType? exportType = default, int expiration = 86400, string filename = default, bool storeS3 = false, string s3Filepath = default, string s3Bucket = default, string varVersion = default)
        {
            // to ensure "templateId" is required (not null)
            if (templateId == null)
            {
                throw new ArgumentNullException("templateId is a required property for CreateImageRequest and cannot be null");
            }
            this.TemplateId = templateId;
            this.Modifications = modifications;
            this.Data = data;
            this.Format = format;
            this.Width = width;
            this.Quality = quality;
            this.ExportType = exportType;
            this.Expiration = expiration;
            this.Filename = filename;
            this.StoreS3 = storeS3;
            this.S3Filepath = s3Filepath;
            this.S3Bucket = s3Bucket;
            this.VarVersion = varVersion;
        }

        /// <summary>
        /// Template short ID (12 characters)
        /// </summary>
        /// <value>Template short ID (12 characters)</value>
        [DataMember(Name = "template_id", IsRequired = true, EmitDefaultValue = true)]
        public string TemplateId { get; set; }

        /// <summary>
        /// Gets or Sets Modifications
        /// </summary>
        [DataMember(Name = "modifications", EmitDefaultValue = true)]
        public List<Modification> Modifications { get; set; }

        /// <summary>
        /// Optional key-value data merged into &#x60;{{ }}&#x60; template variables. For most image templates, prefer &#x60;modifications&#x60; instead.
        /// </summary>
        /// <value>Optional key-value data merged into &#x60;{{ }}&#x60; template variables. For most image templates, prefer &#x60;modifications&#x60; instead.</value>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public Dictionary<string, Object> Data { get; set; }

        /// <summary>
        /// Gets or Sets Width
        /// </summary>
        [DataMember(Name = "width", EmitDefaultValue = true)]
        public int? Width { get; set; }

        /// <summary>
        /// Compression quality for &#x60;jpeg&#x60;/&#x60;webp&#x60; (1-100). Ignored for &#x60;png&#x60;.
        /// </summary>
        /// <value>Compression quality for &#x60;jpeg&#x60;/&#x60;webp&#x60; (1-100). Ignored for &#x60;png&#x60;.</value>
        [DataMember(Name = "quality", EmitDefaultValue = false)]
        public int Quality { get; set; }

        /// <summary>
        /// URL expiration in seconds. Min: 60 (1 min), Max: 604800 (7 days). Only applies to &#x60;url&#x60; export type.
        /// </summary>
        /// <value>URL expiration in seconds. Min: 60 (1 min), Max: 604800 (7 days). Only applies to &#x60;url&#x60; export type.</value>
        [DataMember(Name = "expiration", EmitDefaultValue = false)]
        public int Expiration { get; set; }

        /// <summary>
        /// Gets or Sets Filename
        /// </summary>
        [DataMember(Name = "filename", EmitDefaultValue = true)]
        public string Filename { get; set; }

        /// <summary>
        /// Upload to your configured S3 bucket instead of CDN
        /// </summary>
        /// <value>Upload to your configured S3 bucket instead of CDN</value>
        [DataMember(Name = "store_s3", EmitDefaultValue = true)]
        public bool StoreS3 { get; set; }

        /// <summary>
        /// Gets or Sets S3Filepath
        /// </summary>
        [DataMember(Name = "s3_filepath", EmitDefaultValue = true)]
        public string S3Filepath { get; set; }

        /// <summary>
        /// Gets or Sets S3Bucket
        /// </summary>
        [DataMember(Name = "s3_bucket", EmitDefaultValue = true)]
        public string S3Bucket { get; set; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [DataMember(Name = "version", EmitDefaultValue = true)]
        public string VarVersion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateImageRequest {\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  Modifications: ").Append(Modifications).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Quality: ").Append(Quality).Append("\n");
            sb.Append("  ExportType: ").Append(ExportType).Append("\n");
            sb.Append("  Expiration: ").Append(Expiration).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("  StoreS3: ").Append(StoreS3).Append("\n");
            sb.Append("  S3Filepath: ").Append(S3Filepath).Append("\n");
            sb.Append("  S3Bucket: ").Append(S3Bucket).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // TemplateId (string) maxLength
            if (this.TemplateId != null && this.TemplateId.Length > 12)
            {
                yield return new ValidationResult("Invalid value for TemplateId, length must be less than 12.", new [] { "TemplateId" });
            }

            // TemplateId (string) minLength
            if (this.TemplateId != null && this.TemplateId.Length < 12)
            {
                yield return new ValidationResult("Invalid value for TemplateId, length must be greater than 12.", new [] { "TemplateId" });
            }

            // Width (int?) maximum
            if (this.Width > (int?)4000)
            {
                yield return new ValidationResult("Invalid value for Width, must be a value less than or equal to 4000.", new [] { "Width" });
            }

            // Width (int?) minimum
            if (this.Width < (int?)100)
            {
                yield return new ValidationResult("Invalid value for Width, must be a value greater than or equal to 100.", new [] { "Width" });
            }

            // Quality (int) maximum
            if (this.Quality > (int)100)
            {
                yield return new ValidationResult("Invalid value for Quality, must be a value less than or equal to 100.", new [] { "Quality" });
            }

            // Quality (int) minimum
            if (this.Quality < (int)1)
            {
                yield return new ValidationResult("Invalid value for Quality, must be a value greater than or equal to 1.", new [] { "Quality" });
            }

            // Expiration (int) maximum
            if (this.Expiration > (int)604800)
            {
                yield return new ValidationResult("Invalid value for Expiration, must be a value less than or equal to 604800.", new [] { "Expiration" });
            }

            // Expiration (int) minimum
            if (this.Expiration < (int)60)
            {
                yield return new ValidationResult("Invalid value for Expiration, must be a value greater than or equal to 60.", new [] { "Expiration" });
            }

            // Filename (string) maxLength
            if (this.Filename != null && this.Filename.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Filename, length must be less than 100.", new [] { "Filename" });
            }

            if (this.Filename != null) {
                // Filename (string) pattern
                Regex regexFilename = new Regex(@"^[a-zA-Z0-9_\-\.]+$", RegexOptions.CultureInvariant);
                if (!regexFilename.Match(this.Filename).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Filename, must match a pattern of " + regexFilename, new [] { "Filename" });
                }
            }

            // S3Filepath (string) maxLength
            if (this.S3Filepath != null && this.S3Filepath.Length > 500)
            {
                yield return new ValidationResult("Invalid value for S3Filepath, length must be less than 500.", new [] { "S3Filepath" });
            }

            if (this.S3Filepath != null) {
                // S3Filepath (string) pattern
                Regex regexS3Filepath = new Regex(@"^[a-zA-Z0-9_\-\./]+$", RegexOptions.CultureInvariant);
                if (!regexS3Filepath.Match(this.S3Filepath).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for S3Filepath, must match a pattern of " + regexS3Filepath, new [] { "S3Filepath" });
                }
            }

            // S3Bucket (string) maxLength
            if (this.S3Bucket != null && this.S3Bucket.Length > 63)
            {
                yield return new ValidationResult("Invalid value for S3Bucket, length must be less than 63.", new [] { "S3Bucket" });
            }

            // S3Bucket (string) minLength
            if (this.S3Bucket != null && this.S3Bucket.Length < 3)
            {
                yield return new ValidationResult("Invalid value for S3Bucket, length must be greater than 3.", new [] { "S3Bucket" });
            }

            if (this.S3Bucket != null) {
                // S3Bucket (string) pattern
                Regex regexS3Bucket = new Regex(@"^[a-z0-9][a-z0-9.\-]*[a-z0-9]$", RegexOptions.CultureInvariant);
                if (!regexS3Bucket.Match(this.S3Bucket).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for S3Bucket, must match a pattern of " + regexS3Bucket, new [] { "S3Bucket" });
                }
            }

            // VarVersion (string) maxLength
            if (this.VarVersion != null && this.VarVersion.Length > 50)
            {
                yield return new ValidationResult("Invalid value for VarVersion, length must be less than 50.", new [] { "VarVersion" });
            }

            yield break;
        }
    }

}
