/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// CreateAgentTemplateRequest
    /// </summary>
    [DataContract(Name = "CreateAgentTemplateRequest")]
    public partial class CreateAgentTemplateRequest : IValidatableObject
    {
        /// <summary>
        /// Defines Preset
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PresetEnum
        {
            /// <summary>
            /// Enum InstagramSquare for value: instagram-square
            /// </summary>
            [EnumMember(Value = "instagram-square")]
            InstagramSquare = 1,

            /// <summary>
            /// Enum InstagramStory for value: instagram-story
            /// </summary>
            [EnumMember(Value = "instagram-story")]
            InstagramStory = 2,

            /// <summary>
            /// Enum OgImage for value: og-image
            /// </summary>
            [EnumMember(Value = "og-image")]
            OgImage = 3,

            /// <summary>
            /// Enum TwitterCard for value: twitter-card
            /// </summary>
            [EnumMember(Value = "twitter-card")]
            TwitterCard = 4,

            /// <summary>
            /// Enum PinterestPin for value: pinterest-pin
            /// </summary>
            [EnumMember(Value = "pinterest-pin")]
            PinterestPin = 5,

            /// <summary>
            /// Enum Square512 for value: square-512
            /// </summary>
            [EnumMember(Value = "square-512")]
            Square512 = 6
        }


        /// <summary>
        /// Gets or Sets Preset
        /// </summary>
        [DataMember(Name = "preset", EmitDefaultValue = true)]
        public PresetEnum? Preset { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAgentTemplateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateAgentTemplateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAgentTemplateRequest" /> class.
        /// </summary>
        /// <param name="instructions">What the template should look like and which layers it needs, in natural language. (required).</param>
        /// <param name="name">Template name (required).</param>
        /// <param name="preset">preset.</param>
        /// <param name="width">width.</param>
        /// <param name="height">height.</param>
        /// <param name="brand">brand.</param>
        public CreateAgentTemplateRequest(string instructions = default, string name = default, PresetEnum? preset = default, int? width = default, int? height = default, BrandInputs brand = default)
        {
            // to ensure "instructions" is required (not null)
            if (instructions == null)
            {
                throw new ArgumentNullException("instructions is a required property for CreateAgentTemplateRequest and cannot be null");
            }
            this.Instructions = instructions;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateAgentTemplateRequest and cannot be null");
            }
            this.Name = name;
            this.Preset = preset;
            this.Width = width;
            this.Height = height;
            this.Brand = brand;
        }

        /// <summary>
        /// What the template should look like and which layers it needs, in natural language.
        /// </summary>
        /// <value>What the template should look like and which layers it needs, in natural language.</value>
        [DataMember(Name = "instructions", IsRequired = true, EmitDefaultValue = true)]
        public string Instructions { get; set; }

        /// <summary>
        /// Template name
        /// </summary>
        /// <value>Template name</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Width
        /// </summary>
        [DataMember(Name = "width", EmitDefaultValue = true)]
        public int? Width { get; set; }

        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [DataMember(Name = "height", EmitDefaultValue = true)]
        public int? Height { get; set; }

        /// <summary>
        /// Gets or Sets Brand
        /// </summary>
        [DataMember(Name = "brand", EmitDefaultValue = true)]
        public BrandInputs Brand { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateAgentTemplateRequest {\n");
            sb.Append("  Instructions: ").Append(Instructions).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Preset: ").Append(Preset).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Brand: ").Append(Brand).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Instructions (string) maxLength
            if (this.Instructions != null && this.Instructions.Length > 4000)
            {
                yield return new ValidationResult("Invalid value for Instructions, length must be less than 4000.", new [] { "Instructions" });
            }

            // Instructions (string) minLength
            if (this.Instructions != null && this.Instructions.Length < 10)
            {
                yield return new ValidationResult("Invalid value for Instructions, length must be greater than 10.", new [] { "Instructions" });
            }

            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 100.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Width (int?) maximum
            if (this.Width > (int?)8000)
            {
                yield return new ValidationResult("Invalid value for Width, must be a value less than or equal to 8000.", new [] { "Width" });
            }

            // Width (int?) minimum
            if (this.Width < (int?)16)
            {
                yield return new ValidationResult("Invalid value for Width, must be a value greater than or equal to 16.", new [] { "Width" });
            }

            // Height (int?) maximum
            if (this.Height > (int?)8000)
            {
                yield return new ValidationResult("Invalid value for Height, must be a value less than or equal to 8000.", new [] { "Height" });
            }

            // Height (int?) minimum
            if (this.Height < (int?)16)
            {
                yield return new ValidationResult("Invalid value for Height, must be a value greater than or equal to 16.", new [] { "Height" });
            }

            yield break;
        }
    }

}
