/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.9.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Request to create a version snapshot
    /// </summary>
    [DataContract(Name = "CreateVersionRequest")]
    public partial class CreateVersionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateVersionRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateVersionRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateVersionRequest" /> class.
        /// </summary>
        /// <param name="tag">Version tag (e.g. &#39;prod&#39;, &#39;staging&#39;, &#39;v1&#39;). Lowercase alphanumeric with hyphens/underscores, 2-50 chars. (required).</param>
        /// <param name="description">description.</param>
        public CreateVersionRequest(string tag = default, string description = default)
        {
            // to ensure "tag" is required (not null)
            if (tag == null)
            {
                throw new ArgumentNullException("tag is a required property for CreateVersionRequest and cannot be null");
            }
            this.Tag = tag;
            this.Description = description;
        }

        /// <summary>
        /// Version tag (e.g. &#39;prod&#39;, &#39;staging&#39;, &#39;v1&#39;). Lowercase alphanumeric with hyphens/underscores, 2-50 chars.
        /// </summary>
        /// <value>Version tag (e.g. &#39;prod&#39;, &#39;staging&#39;, &#39;v1&#39;). Lowercase alphanumeric with hyphens/underscores, 2-50 chars.</value>
        [DataMember(Name = "tag", IsRequired = true, EmitDefaultValue = true)]
        public string Tag { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateVersionRequest {\n");
            sb.Append("  Tag: ").Append(Tag).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Tag (string) maxLength
            if (this.Tag != null && this.Tag.Length > 50)
            {
                yield return new ValidationResult("Invalid value for Tag, length must be less than 50.", new [] { "Tag" });
            }

            // Tag (string) minLength
            if (this.Tag != null && this.Tag.Length < 2)
            {
                yield return new ValidationResult("Invalid value for Tag, length must be greater than 2.", new [] { "Tag" });
            }

            if (this.Tag != null) {
                // Tag (string) pattern
                Regex regexTag = new Regex(@"^[a-z0-9][a-z0-9_-]{0,48}[a-z0-9]$", RegexOptions.CultureInvariant);
                if (!regexTag.Match(this.Tag).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Tag, must match a pattern of " + regexTag, new [] { "Tag" });
                }
            }

            // Description (string) maxLength
            if (this.Description != null && this.Description.Length > 500)
            {
                yield return new ValidationResult("Invalid value for Description, length must be less than 500.", new [] { "Description" });
            }

            yield break;
        }
    }

}
