/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Response for URL export type
    /// </summary>
    [DataContract(Name = "CreateImageResponse")]
    public partial class CreateImageResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateImageResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateImageResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateImageResponse" /> class.
        /// </summary>
        /// <param name="url">Signed URL to download the image (expires after specified time) (required).</param>
        /// <param name="filename">Filename of the generated image (required).</param>
        /// <param name="creditsRemaining">Remaining credits after this request (required).</param>
        /// <param name="expiresIn">Seconds until the signed URL expires (required).</param>
        /// <param name="warnings">warnings.</param>
        public CreateImageResponse(string url = default, string filename = default, int creditsRemaining = default, int expiresIn = default, List<string> warnings = default)
        {
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for CreateImageResponse and cannot be null");
            }
            this.Url = url;
            // to ensure "filename" is required (not null)
            if (filename == null)
            {
                throw new ArgumentNullException("filename is a required property for CreateImageResponse and cannot be null");
            }
            this.Filename = filename;
            this.CreditsRemaining = creditsRemaining;
            this.ExpiresIn = expiresIn;
            this.Warnings = warnings;
        }

        /// <summary>
        /// Signed URL to download the image (expires after specified time)
        /// </summary>
        /// <value>Signed URL to download the image (expires after specified time)</value>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Filename of the generated image
        /// </summary>
        /// <value>Filename of the generated image</value>
        [DataMember(Name = "filename", IsRequired = true, EmitDefaultValue = true)]
        public string Filename { get; set; }

        /// <summary>
        /// Remaining credits after this request
        /// </summary>
        /// <value>Remaining credits after this request</value>
        [DataMember(Name = "credits_remaining", IsRequired = true, EmitDefaultValue = true)]
        public int CreditsRemaining { get; set; }

        /// <summary>
        /// Seconds until the signed URL expires
        /// </summary>
        /// <value>Seconds until the signed URL expires</value>
        [DataMember(Name = "expires_in", IsRequired = true, EmitDefaultValue = true)]
        public int ExpiresIn { get; set; }

        /// <summary>
        /// Gets or Sets Warnings
        /// </summary>
        [DataMember(Name = "warnings", EmitDefaultValue = true)]
        public List<string> Warnings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateImageResponse {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("  CreditsRemaining: ").Append(CreditsRemaining).Append("\n");
            sb.Append("  ExpiresIn: ").Append(ExpiresIn).Append("\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
