/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// ExtractPdfPagesRequest
    /// </summary>
    [DataContract(Name = "ExtractPdfPagesRequest")]
    public partial class ExtractPdfPagesRequest : IValidatableObject
    {

        /// <summary>
        /// &#x60;url&#x60; uploads to CDN and returns URL, &#x60;binary&#x60; returns raw PDF bytes
        /// </summary>
        /// <value>&#x60;url&#x60; uploads to CDN and returns URL, &#x60;binary&#x60; returns raw PDF bytes</value>
        [DataMember(Name = "export_type", EmitDefaultValue = false)]
        public AppRoutersV1PdfToolsExportType? ExportType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ExtractPdfPagesRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ExtractPdfPagesRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ExtractPdfPagesRequest" /> class.
        /// </summary>
        /// <param name="exportType">&#x60;url&#x60; uploads to CDN and returns URL, &#x60;binary&#x60; returns raw PDF bytes.</param>
        /// <param name="expiration">URL expiration in seconds. Min 60, max 604800. Only applies to &#x60;url&#x60; export type. (default to 86400).</param>
        /// <param name="filename">filename.</param>
        /// <param name="pdfUrl">pdfUrl.</param>
        /// <param name="pdfBase64">pdfBase64.</param>
        /// <param name="pages">1-indexed page selection. Supports ranges and singles separated by commas, e.g. &#x60;1-3, 5, 7-9&#x60;. Order is preserved (&#x60;5,1,3&#x60; outputs those 3 pages in that order). (required).</param>
        public ExtractPdfPagesRequest(AppRoutersV1PdfToolsExportType? exportType = default, int expiration = 86400, string filename = default, string pdfUrl = default, string pdfBase64 = default, string pages = default)
        {
            // to ensure "pages" is required (not null)
            if (pages == null)
            {
                throw new ArgumentNullException("pages is a required property for ExtractPdfPagesRequest and cannot be null");
            }
            this.Pages = pages;
            this.ExportType = exportType;
            this.Expiration = expiration;
            this.Filename = filename;
            this.PdfUrl = pdfUrl;
            this.PdfBase64 = pdfBase64;
        }

        /// <summary>
        /// URL expiration in seconds. Min 60, max 604800. Only applies to &#x60;url&#x60; export type.
        /// </summary>
        /// <value>URL expiration in seconds. Min 60, max 604800. Only applies to &#x60;url&#x60; export type.</value>
        [DataMember(Name = "expiration", EmitDefaultValue = false)]
        public int Expiration { get; set; }

        /// <summary>
        /// Gets or Sets Filename
        /// </summary>
        [DataMember(Name = "filename", EmitDefaultValue = true)]
        public string Filename { get; set; }

        /// <summary>
        /// Gets or Sets PdfUrl
        /// </summary>
        [DataMember(Name = "pdf_url", EmitDefaultValue = true)]
        public string PdfUrl { get; set; }

        /// <summary>
        /// Gets or Sets PdfBase64
        /// </summary>
        [DataMember(Name = "pdf_base64", EmitDefaultValue = true)]
        public string PdfBase64 { get; set; }

        /// <summary>
        /// 1-indexed page selection. Supports ranges and singles separated by commas, e.g. &#x60;1-3, 5, 7-9&#x60;. Order is preserved (&#x60;5,1,3&#x60; outputs those 3 pages in that order).
        /// </summary>
        /// <value>1-indexed page selection. Supports ranges and singles separated by commas, e.g. &#x60;1-3, 5, 7-9&#x60;. Order is preserved (&#x60;5,1,3&#x60; outputs those 3 pages in that order).</value>
        [DataMember(Name = "pages", IsRequired = true, EmitDefaultValue = true)]
        public string Pages { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ExtractPdfPagesRequest {\n");
            sb.Append("  ExportType: ").Append(ExportType).Append("\n");
            sb.Append("  Expiration: ").Append(Expiration).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("  PdfUrl: ").Append(PdfUrl).Append("\n");
            sb.Append("  PdfBase64: ").Append(PdfBase64).Append("\n");
            sb.Append("  Pages: ").Append(Pages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Expiration (int) maximum
            if (this.Expiration > (int)604800)
            {
                yield return new ValidationResult("Invalid value for Expiration, must be a value less than or equal to 604800.", new [] { "Expiration" });
            }

            // Expiration (int) minimum
            if (this.Expiration < (int)60)
            {
                yield return new ValidationResult("Invalid value for Expiration, must be a value greater than or equal to 60.", new [] { "Expiration" });
            }

            // Filename (string) maxLength
            if (this.Filename != null && this.Filename.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Filename, length must be less than 100.", new [] { "Filename" });
            }

            if (this.Filename != null) {
                // Filename (string) pattern
                Regex regexFilename = new Regex(@"^[a-zA-Z0-9_\-\.]+$", RegexOptions.CultureInvariant);
                if (!regexFilename.Match(this.Filename).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Filename, must match a pattern of " + regexFilename, new [] { "Filename" });
                }
            }

            yield break;
        }
    }

}
