/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.11.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Image output format options
    /// </summary>
    /// <value>Image output format options</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ImageFormat
    {
        /// <summary>
        /// Enum Png for value: png
        /// </summary>
        [EnumMember(Value = "png")]
        Png = 1,

        /// <summary>
        /// Enum Jpeg for value: jpeg
        /// </summary>
        [EnumMember(Value = "jpeg")]
        Jpeg = 2,

        /// <summary>
        /// Enum Webp for value: webp
        /// </summary>
        [EnumMember(Value = "webp")]
        Webp = 3
    }

}
