/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.11.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// MergePdfRequest
    /// </summary>
    [DataContract(Name = "MergePdfRequest")]
    public partial class MergePdfRequest : IValidatableObject
    {

        /// <summary>
        /// &#x60;url&#x60; uploads to CDN and returns URL, &#x60;binary&#x60; returns raw PDF bytes
        /// </summary>
        /// <value>&#x60;url&#x60; uploads to CDN and returns URL, &#x60;binary&#x60; returns raw PDF bytes</value>
        [DataMember(Name = "export_type", EmitDefaultValue = false)]
        public AppRoutersV1PdfToolsExportType? ExportType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MergePdfRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MergePdfRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MergePdfRequest" /> class.
        /// </summary>
        /// <param name="exportType">&#x60;url&#x60; uploads to CDN and returns URL, &#x60;binary&#x60; returns raw PDF bytes.</param>
        /// <param name="expiration">URL expiration in seconds. Min 60, max 604800. Only applies to &#x60;url&#x60; export type. (default to 86400).</param>
        /// <param name="filename">filename.</param>
        /// <param name="pdfs">Ordered list of PDFs to merge. Each entry has either &#x60;pdf_url&#x60; or &#x60;pdf_base64&#x60;. Minimum 2. (required).</param>
        public MergePdfRequest(AppRoutersV1PdfToolsExportType? exportType = default, int expiration = 86400, string filename = default, List<PdfInput> pdfs = default)
        {
            // to ensure "pdfs" is required (not null)
            if (pdfs == null)
            {
                throw new ArgumentNullException("pdfs is a required property for MergePdfRequest and cannot be null");
            }
            this.Pdfs = pdfs;
            this.ExportType = exportType;
            this.Expiration = expiration;
            this.Filename = filename;
        }

        /// <summary>
        /// URL expiration in seconds. Min 60, max 604800. Only applies to &#x60;url&#x60; export type.
        /// </summary>
        /// <value>URL expiration in seconds. Min 60, max 604800. Only applies to &#x60;url&#x60; export type.</value>
        [DataMember(Name = "expiration", EmitDefaultValue = false)]
        public int Expiration { get; set; }

        /// <summary>
        /// Gets or Sets Filename
        /// </summary>
        [DataMember(Name = "filename", EmitDefaultValue = true)]
        public string Filename { get; set; }

        /// <summary>
        /// Ordered list of PDFs to merge. Each entry has either &#x60;pdf_url&#x60; or &#x60;pdf_base64&#x60;. Minimum 2.
        /// </summary>
        /// <value>Ordered list of PDFs to merge. Each entry has either &#x60;pdf_url&#x60; or &#x60;pdf_base64&#x60;. Minimum 2.</value>
        [DataMember(Name = "pdfs", IsRequired = true, EmitDefaultValue = true)]
        public List<PdfInput> Pdfs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MergePdfRequest {\n");
            sb.Append("  ExportType: ").Append(ExportType).Append("\n");
            sb.Append("  Expiration: ").Append(Expiration).Append("\n");
            sb.Append("  Filename: ").Append(Filename).Append("\n");
            sb.Append("  Pdfs: ").Append(Pdfs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Expiration (int) maximum
            if (this.Expiration > (int)604800)
            {
                yield return new ValidationResult("Invalid value for Expiration, must be a value less than or equal to 604800.", new [] { "Expiration" });
            }

            // Expiration (int) minimum
            if (this.Expiration < (int)60)
            {
                yield return new ValidationResult("Invalid value for Expiration, must be a value greater than or equal to 60.", new [] { "Expiration" });
            }

            // Filename (string) maxLength
            if (this.Filename != null && this.Filename.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Filename, length must be less than 100.", new [] { "Filename" });
            }

            if (this.Filename != null) {
                // Filename (string) pattern
                Regex regexFilename = new Regex(@"^[a-zA-Z0-9_\-\.]+$", RegexOptions.CultureInvariant);
                if (!regexFilename.Match(this.Filename).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Filename, must match a pattern of " + regexFilename, new [] { "Filename" });
                }
            }

            yield break;
        }
    }

}
