/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// A single element modification, addressed by layer name.
    /// </summary>
    [DataContract(Name = "Modification")]
    public partial class Modification : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Modification" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Modification() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Modification" /> class.
        /// </summary>
        /// <param name="name">Name of the layer to modify (set via the editor&#39;s Layers panel). Matched against the element&#39;s &#x60;data-layer-name&#x60;, falling back to its &#x60;id&#x60;. (required).</param>
        /// <param name="text">text.</param>
        /// <param name="imageUrl">imageUrl.</param>
        /// <param name="color">color.</param>
        /// <param name="background">background.</param>
        /// <param name="hidden">hidden.</param>
        public Modification(string name = default, string text = default, string imageUrl = default, string color = default, string background = default, bool? hidden = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for Modification and cannot be null");
            }
            this.Name = name;
            this.Text = text;
            this.ImageUrl = imageUrl;
            this.Color = color;
            this.Background = background;
            this.Hidden = hidden;
        }

        /// <summary>
        /// Name of the layer to modify (set via the editor&#39;s Layers panel). Matched against the element&#39;s &#x60;data-layer-name&#x60;, falling back to its &#x60;id&#x60;.
        /// </summary>
        /// <value>Name of the layer to modify (set via the editor&#39;s Layers panel). Matched against the element&#39;s &#x60;data-layer-name&#x60;, falling back to its &#x60;id&#x60;.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [DataMember(Name = "text", EmitDefaultValue = true)]
        public string Text { get; set; }

        /// <summary>
        /// Gets or Sets ImageUrl
        /// </summary>
        [DataMember(Name = "image_url", EmitDefaultValue = true)]
        public string ImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets Color
        /// </summary>
        [DataMember(Name = "color", EmitDefaultValue = true)]
        public string Color { get; set; }

        /// <summary>
        /// Gets or Sets Background
        /// </summary>
        [DataMember(Name = "background", EmitDefaultValue = true)]
        public string Background { get; set; }

        /// <summary>
        /// Gets or Sets Hidden
        /// </summary>
        [DataMember(Name = "hidden", EmitDefaultValue = true)]
        public bool? Hidden { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Modification {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("  ImageUrl: ").Append(ImageUrl).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("  Background: ").Append(Background).Append("\n");
            sb.Append("  Hidden: ").Append(Hidden).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 200)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 200.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Text (string) maxLength
            if (this.Text != null && this.Text.Length > 10000)
            {
                yield return new ValidationResult("Invalid value for Text, length must be less than 10000.", new [] { "Text" });
            }

            // ImageUrl (string) maxLength
            if (this.ImageUrl != null && this.ImageUrl.Length > 2000)
            {
                yield return new ValidationResult("Invalid value for ImageUrl, length must be less than 2000.", new [] { "ImageUrl" });
            }

            if (this.ImageUrl != null) {
                // ImageUrl (string) pattern
                Regex regexImageUrl = new Regex(@"^https?://", RegexOptions.CultureInvariant);
                if (!regexImageUrl.Match(this.ImageUrl).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ImageUrl, must match a pattern of " + regexImageUrl, new [] { "ImageUrl" });
                }
            }

            // Color (string) maxLength
            if (this.Color != null && this.Color.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Color, length must be less than 100.", new [] { "Color" });
            }

            // Background (string) maxLength
            if (this.Background != null && this.Background.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Background, length must be less than 100.", new [] { "Background" });
            }

            yield break;
        }
    }

}
