/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.11.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Either pdf_url (HTTPS) or pdf_base64 — exactly one.
    /// </summary>
    [DataContract(Name = "PdfInput")]
    public partial class PdfInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PdfInput" /> class.
        /// </summary>
        /// <param name="pdfUrl">pdfUrl.</param>
        /// <param name="pdfBase64">pdfBase64.</param>
        public PdfInput(string pdfUrl = default, string pdfBase64 = default)
        {
            this.PdfUrl = pdfUrl;
            this.PdfBase64 = pdfBase64;
        }

        /// <summary>
        /// Gets or Sets PdfUrl
        /// </summary>
        [DataMember(Name = "pdf_url", EmitDefaultValue = true)]
        public string PdfUrl { get; set; }

        /// <summary>
        /// Gets or Sets PdfBase64
        /// </summary>
        [DataMember(Name = "pdf_base64", EmitDefaultValue = true)]
        public string PdfBase64 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PdfInput {\n");
            sb.Append("  PdfUrl: ").Append(PdfUrl).Append("\n");
            sb.Append("  PdfBase64: ").Append(PdfBase64).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
