/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.9.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// PDF variant for standards-compliant output (PDF/A).
    /// </summary>
    /// <value>PDF variant for standards-compliant output (PDF/A).</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PdfVariant
    {
        /// <summary>
        /// Enum PdfA1b for value: pdf/a-1b
        /// </summary>
        [EnumMember(Value = "pdf/a-1b")]
        PdfA1b = 1,

        /// <summary>
        /// Enum PdfA2b for value: pdf/a-2b
        /// </summary>
        [EnumMember(Value = "pdf/a-2b")]
        PdfA2b = 2,

        /// <summary>
        /// Enum PdfA3b for value: pdf/a-3b
        /// </summary>
        [EnumMember(Value = "pdf/a-3b")]
        PdfA3b = 3
    }

}
