/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// ReviseAgentTemplateRequest
    /// </summary>
    [DataContract(Name = "ReviseAgentTemplateRequest")]
    public partial class ReviseAgentTemplateRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReviseAgentTemplateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReviseAgentTemplateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReviseAgentTemplateRequest" /> class.
        /// </summary>
        /// <param name="feedback">Natural-language feedback on the current template. (required).</param>
        /// <param name="brand">brand.</param>
        public ReviseAgentTemplateRequest(string feedback = default, BrandInputs brand = default)
        {
            // to ensure "feedback" is required (not null)
            if (feedback == null)
            {
                throw new ArgumentNullException("feedback is a required property for ReviseAgentTemplateRequest and cannot be null");
            }
            this.Feedback = feedback;
            this.Brand = brand;
        }

        /// <summary>
        /// Natural-language feedback on the current template.
        /// </summary>
        /// <value>Natural-language feedback on the current template.</value>
        [DataMember(Name = "feedback", IsRequired = true, EmitDefaultValue = true)]
        public string Feedback { get; set; }

        /// <summary>
        /// Gets or Sets Brand
        /// </summary>
        [DataMember(Name = "brand", EmitDefaultValue = true)]
        public BrandInputs Brand { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReviseAgentTemplateRequest {\n");
            sb.Append("  Feedback: ").Append(Feedback).Append("\n");
            sb.Append("  Brand: ").Append(Brand).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Feedback (string) maxLength
            if (this.Feedback != null && this.Feedback.Length > 4000)
            {
                yield return new ValidationResult("Invalid value for Feedback, length must be less than 4000.", new [] { "Feedback" });
            }

            // Feedback (string) minLength
            if (this.Feedback != null && this.Feedback.Length < 5)
            {
                yield return new ValidationResult("Invalid value for Feedback, length must be greater than 5.", new [] { "Feedback" });
            }

            yield break;
        }
    }

}
