/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.9.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Request to set the default version
    /// </summary>
    [DataContract(Name = "SetDefaultVersionRequest")]
    public partial class SetDefaultVersionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetDefaultVersionRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SetDefaultVersionRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetDefaultVersionRequest" /> class.
        /// </summary>
        /// <param name="versionNumber">Version number to set as default (required).</param>
        public SetDefaultVersionRequest(int versionNumber = default)
        {
            this.VersionNumber = versionNumber;
        }

        /// <summary>
        /// Version number to set as default
        /// </summary>
        /// <value>Version number to set as default</value>
        [DataMember(Name = "version_number", IsRequired = true, EmitDefaultValue = true)]
        public int VersionNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetDefaultVersionRequest {\n");
            sb.Append("  VersionNumber: ").Append(VersionNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
