/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// Response for template layers endpoint
    /// </summary>
    [DataContract(Name = "TemplateLayersResponse")]
    public partial class TemplateLayersResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateLayersResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TemplateLayersResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateLayersResponse" /> class.
        /// </summary>
        /// <param name="layers">layers (required).</param>
        /// <param name="warnings">Non-fatal issues (e.g. duplicate layer names).</param>
        public TemplateLayersResponse(List<TemplateLayer> layers = default, List<string> warnings = default)
        {
            // to ensure "layers" is required (not null)
            if (layers == null)
            {
                throw new ArgumentNullException("layers is a required property for TemplateLayersResponse and cannot be null");
            }
            this.Layers = layers;
            this.Warnings = warnings;
        }

        /// <summary>
        /// Gets or Sets Layers
        /// </summary>
        [DataMember(Name = "layers", IsRequired = true, EmitDefaultValue = true)]
        public List<TemplateLayer> Layers { get; set; }

        /// <summary>
        /// Non-fatal issues (e.g. duplicate layer names)
        /// </summary>
        /// <value>Non-fatal issues (e.g. duplicate layer names)</value>
        [DataMember(Name = "warnings", EmitDefaultValue = false)]
        public List<string> Warnings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TemplateLayersResponse {\n");
            sb.Append("  Layers: ").Append(Layers).Append("\n");
            sb.Append("  Warnings: ").Append(Warnings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
