/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = TemplateFox.SDK.Client.FileParameter;
using OpenAPIDateConverter = TemplateFox.SDK.Client.OpenAPIDateConverter;

namespace TemplateFox.SDK.Model
{
    /// <summary>
    /// An addressable layer of a template (modifications API)
    /// </summary>
    [DataContract(Name = "TemplateLayer")]
    public partial class TemplateLayer : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateLayer" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TemplateLayer() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateLayer" /> class.
        /// </summary>
        /// <param name="name">Layer name — the value to use in &#x60;modifications[].name&#x60; (required).</param>
        /// <param name="tag">HTML tag of the element (required).</param>
        /// <param name="type">Layer type: &#x60;background&#x60;, &#x60;image&#x60;, &#x60;text&#x60; or &#x60;shape&#x60; (required).</param>
        /// <param name="currentText">currentText.</param>
        /// <param name="modifiable">Modification fields that apply to this layer (required).</param>
        public TemplateLayer(string name = default, string tag = default, string type = default, string currentText = default, List<string> modifiable = default)
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for TemplateLayer and cannot be null");
            }
            this.Name = name;
            // to ensure "tag" is required (not null)
            if (tag == null)
            {
                throw new ArgumentNullException("tag is a required property for TemplateLayer and cannot be null");
            }
            this.Tag = tag;
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new ArgumentNullException("type is a required property for TemplateLayer and cannot be null");
            }
            this.Type = type;
            // to ensure "modifiable" is required (not null)
            if (modifiable == null)
            {
                throw new ArgumentNullException("modifiable is a required property for TemplateLayer and cannot be null");
            }
            this.Modifiable = modifiable;
            this.CurrentText = currentText;
        }

        /// <summary>
        /// Layer name — the value to use in &#x60;modifications[].name&#x60;
        /// </summary>
        /// <value>Layer name — the value to use in &#x60;modifications[].name&#x60;</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// HTML tag of the element
        /// </summary>
        /// <value>HTML tag of the element</value>
        [DataMember(Name = "tag", IsRequired = true, EmitDefaultValue = true)]
        public string Tag { get; set; }

        /// <summary>
        /// Layer type: &#x60;background&#x60;, &#x60;image&#x60;, &#x60;text&#x60; or &#x60;shape&#x60;
        /// </summary>
        /// <value>Layer type: &#x60;background&#x60;, &#x60;image&#x60;, &#x60;text&#x60; or &#x60;shape&#x60;</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets CurrentText
        /// </summary>
        [DataMember(Name = "current_text", EmitDefaultValue = true)]
        public string CurrentText { get; set; }

        /// <summary>
        /// Modification fields that apply to this layer
        /// </summary>
        /// <value>Modification fields that apply to this layer</value>
        [DataMember(Name = "modifiable", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Modifiable { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TemplateLayer {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Tag: ").Append(Tag).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  CurrentText: ").Append(CurrentText).Append("\n");
            sb.Append("  Modifiable: ").Append(Modifiable).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
