/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing AppRoutersV1DeliveryExportType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppRoutersV1DeliveryExportTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppRoutersV1DeliveryExportType
        //private AppRoutersV1DeliveryExportType instance;

        public AppRoutersV1DeliveryExportTypeTests()
        {
            // TODO uncomment below to create an instance of AppRoutersV1DeliveryExportType
            //instance = new AppRoutersV1DeliveryExportType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppRoutersV1DeliveryExportType
        /// </summary>
        [Fact]
        public void AppRoutersV1DeliveryExportTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppRoutersV1DeliveryExportType
            //Assert.IsType<AppRoutersV1DeliveryExportType>(instance);
        }
    }
}
