/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing AppRoutersV1AgentJobStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppRoutersV1AgentJobStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppRoutersV1AgentJobStatus
        //private AppRoutersV1AgentJobStatus instance;

        public AppRoutersV1AgentJobStatusTests()
        {
            // TODO uncomment below to create an instance of AppRoutersV1AgentJobStatus
            //instance = new AppRoutersV1AgentJobStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppRoutersV1AgentJobStatus
        /// </summary>
        [Fact]
        public void AppRoutersV1AgentJobStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppRoutersV1AgentJobStatus
            //Assert.IsType<AppRoutersV1AgentJobStatus>(instance);
        }
    }
}
