/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing BrandInputs
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BrandInputsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BrandInputs
        //private BrandInputs instance;

        public BrandInputsTests()
        {
            // TODO uncomment below to create an instance of BrandInputs
            //instance = new BrandInputs();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BrandInputs
        /// </summary>
        [Fact]
        public void BrandInputsInstanceTest()
        {
            // TODO uncomment below to test "IsType" BrandInputs
            //Assert.IsType<BrandInputs>(instance);
        }

        /// <summary>
        /// Test the property 'Colors'
        /// </summary>
        [Fact]
        public void ColorsTest()
        {
            // TODO unit test for the property 'Colors'
        }

        /// <summary>
        /// Test the property 'Fonts'
        /// </summary>
        [Fact]
        public void FontsTest()
        {
            // TODO unit test for the property 'Fonts'
        }

        /// <summary>
        /// Test the property 'AssetUrls'
        /// </summary>
        [Fact]
        public void AssetUrlsTest()
        {
            // TODO unit test for the property 'AssetUrls'
        }
    }
}
