/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing MergePdfRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MergePdfRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MergePdfRequest
        //private MergePdfRequest instance;

        public MergePdfRequestTests()
        {
            // TODO uncomment below to create an instance of MergePdfRequest
            //instance = new MergePdfRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MergePdfRequest
        /// </summary>
        [Fact]
        public void MergePdfRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" MergePdfRequest
            //Assert.IsType<MergePdfRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ExportType'
        /// </summary>
        [Fact]
        public void ExportTypeTest()
        {
            // TODO unit test for the property 'ExportType'
        }

        /// <summary>
        /// Test the property 'Expiration'
        /// </summary>
        [Fact]
        public void ExpirationTest()
        {
            // TODO unit test for the property 'Expiration'
        }

        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }

        /// <summary>
        /// Test the property 'Pdfs'
        /// </summary>
        [Fact]
        public void PdfsTest()
        {
            // TODO unit test for the property 'Pdfs'
        }
    }
}
