/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing PdfInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PdfInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PdfInput
        //private PdfInput instance;

        public PdfInputTests()
        {
            // TODO uncomment below to create an instance of PdfInput
            //instance = new PdfInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PdfInput
        /// </summary>
        [Fact]
        public void PdfInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" PdfInput
            //Assert.IsType<PdfInput>(instance);
        }

        /// <summary>
        /// Test the property 'PdfUrl'
        /// </summary>
        [Fact]
        public void PdfUrlTest()
        {
            // TODO unit test for the property 'PdfUrl'
        }

        /// <summary>
        /// Test the property 'PdfBase64'
        /// </summary>
        [Fact]
        public void PdfBase64Test()
        {
            // TODO unit test for the property 'PdfBase64'
        }
    }
}
