/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing PdfToolsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PdfToolsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PdfToolsResponse
        //private PdfToolsResponse instance;

        public PdfToolsResponseTests()
        {
            // TODO uncomment below to create an instance of PdfToolsResponse
            //instance = new PdfToolsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PdfToolsResponse
        /// </summary>
        [Fact]
        public void PdfToolsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PdfToolsResponse
            //Assert.IsType<PdfToolsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }

        /// <summary>
        /// Test the property 'CreditsRemaining'
        /// </summary>
        [Fact]
        public void CreditsRemainingTest()
        {
            // TODO unit test for the property 'CreditsRemaining'
        }

        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Fact]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }
    }
}
