/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.9.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing PdfVariant
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PdfVariantTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PdfVariant
        //private PdfVariant instance;

        public PdfVariantTests()
        {
            // TODO uncomment below to create an instance of PdfVariant
            //instance = new PdfVariant();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PdfVariant
        /// </summary>
        [Fact]
        public void PdfVariantInstanceTest()
        {
            // TODO uncomment below to test "IsType" PdfVariant
            //Assert.IsType<PdfVariant>(instance);
        }
    }
}
