/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing ReviseAgentTemplateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReviseAgentTemplateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReviseAgentTemplateRequest
        //private ReviseAgentTemplateRequest instance;

        public ReviseAgentTemplateRequestTests()
        {
            // TODO uncomment below to create an instance of ReviseAgentTemplateRequest
            //instance = new ReviseAgentTemplateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReviseAgentTemplateRequest
        /// </summary>
        [Fact]
        public void ReviseAgentTemplateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReviseAgentTemplateRequest
            //Assert.IsType<ReviseAgentTemplateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Feedback'
        /// </summary>
        [Fact]
        public void FeedbackTest()
        {
            // TODO unit test for the property 'Feedback'
        }

        /// <summary>
        /// Test the property 'Brand'
        /// </summary>
        [Fact]
        public void BrandTest()
        {
            // TODO unit test for the property 'Brand'
        }
    }
}
