/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing RotatePdfRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RotatePdfRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RotatePdfRequest
        //private RotatePdfRequest instance;

        public RotatePdfRequestTests()
        {
            // TODO uncomment below to create an instance of RotatePdfRequest
            //instance = new RotatePdfRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RotatePdfRequest
        /// </summary>
        [Fact]
        public void RotatePdfRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RotatePdfRequest
            //Assert.IsType<RotatePdfRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ExportType'
        /// </summary>
        [Fact]
        public void ExportTypeTest()
        {
            // TODO unit test for the property 'ExportType'
        }

        /// <summary>
        /// Test the property 'Expiration'
        /// </summary>
        [Fact]
        public void ExpirationTest()
        {
            // TODO unit test for the property 'Expiration'
        }

        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }

        /// <summary>
        /// Test the property 'PdfUrl'
        /// </summary>
        [Fact]
        public void PdfUrlTest()
        {
            // TODO unit test for the property 'PdfUrl'
        }

        /// <summary>
        /// Test the property 'PdfBase64'
        /// </summary>
        [Fact]
        public void PdfBase64Test()
        {
            // TODO unit test for the property 'PdfBase64'
        }

        /// <summary>
        /// Test the property 'Rotation'
        /// </summary>
        [Fact]
        public void RotationTest()
        {
            // TODO unit test for the property 'Rotation'
        }

        /// <summary>
        /// Test the property 'PageRotations'
        /// </summary>
        [Fact]
        public void PageRotationsTest()
        {
            // TODO unit test for the property 'PageRotations'
        }
    }
}
