/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.9.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing SetDefaultVersionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetDefaultVersionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SetDefaultVersionRequest
        //private SetDefaultVersionRequest instance;

        public SetDefaultVersionRequestTests()
        {
            // TODO uncomment below to create an instance of SetDefaultVersionRequest
            //instance = new SetDefaultVersionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SetDefaultVersionRequest
        /// </summary>
        [Fact]
        public void SetDefaultVersionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SetDefaultVersionRequest
            //Assert.IsType<SetDefaultVersionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Fact]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }
    }
}
