/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateLayersResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateLayersResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateLayersResponse
        //private TemplateLayersResponse instance;

        public TemplateLayersResponseTests()
        {
            // TODO uncomment below to create an instance of TemplateLayersResponse
            //instance = new TemplateLayersResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateLayersResponse
        /// </summary>
        [Fact]
        public void TemplateLayersResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateLayersResponse
            //Assert.IsType<TemplateLayersResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Layers'
        /// </summary>
        [Fact]
        public void LayersTest()
        {
            // TODO unit test for the property 'Layers'
        }

        /// <summary>
        /// Test the property 'Warnings'
        /// </summary>
        [Fact]
        public void WarningsTest()
        {
            // TODO unit test for the property 'Warnings'
        }
    }
}
