/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateLayer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateLayerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateLayer
        //private TemplateLayer instance;

        public TemplateLayerTests()
        {
            // TODO uncomment below to create an instance of TemplateLayer
            //instance = new TemplateLayer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateLayer
        /// </summary>
        [Fact]
        public void TemplateLayerInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateLayer
            //Assert.IsType<TemplateLayer>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Tag'
        /// </summary>
        [Fact]
        public void TagTest()
        {
            // TODO unit test for the property 'Tag'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'CurrentText'
        /// </summary>
        [Fact]
        public void CurrentTextTest()
        {
            // TODO unit test for the property 'CurrentText'
        }

        /// <summary>
        /// Test the property 'Modifiable'
        /// </summary>
        [Fact]
        public void ModifiableTest()
        {
            // TODO unit test for the property 'Modifiable'
        }
    }
}
