/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using TemplateFox.SDK.Model;
using TemplateFox.SDK.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace TemplateFox.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing VersionsListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VersionsListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VersionsListResponse
        //private VersionsListResponse instance;

        public VersionsListResponseTests()
        {
            // TODO uncomment below to create an instance of VersionsListResponse
            //instance = new VersionsListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VersionsListResponse
        /// </summary>
        [Fact]
        public void VersionsListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" VersionsListResponse
            //Assert.IsType<VersionsListResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Versions'
        /// </summary>
        [Fact]
        public void VersionsTest()
        {
            // TODO unit test for the property 'Versions'
        }
    }
}
