/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using TemplateFox.SDK.Client;
using TemplateFox.SDK.Model;

namespace TemplateFox.SDK.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAgentApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a template with the authoring agent
        /// </summary>
        /// <remarks>
        /// Describe the image template you want; the TemplateFox agent authors it for you — valid HTML that renders deterministically AND stays editable in the visual editor, with every layer named and drivable through &#x60;/v1/image/create&#x60; modifications.  The job is asynchronous: poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;. When completed, the response always includes a **preview_url** (rendered PNG) plus the &#x60;template_id&#x60;. Iterate with &#x60;POST /v1/agent/templates/{template_id}/revise&#x60;.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  Creation costs **25 credits**, deducted when the job is queued and fully refunded if the job fails.  ## Canvas  Pass a &#x60;preset&#x60; (instagram-square, instagram-story, og-image, twitter-card, pinterest-pin, square-512) or explicit &#x60;width&#x60; + &#x60;height&#x60; in px.  ## Rate Limits  Standard rate limits apply (60 req/min free, 120 req/min paid).
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAgentTemplateRequest"></param>
        /// <returns>AgentJobCreatedResponse</returns>
        AgentJobCreatedResponse CreateAgentTemplate(CreateAgentTemplateRequest createAgentTemplateRequest);

        /// <summary>
        /// Create a template with the authoring agent
        /// </summary>
        /// <remarks>
        /// Describe the image template you want; the TemplateFox agent authors it for you — valid HTML that renders deterministically AND stays editable in the visual editor, with every layer named and drivable through &#x60;/v1/image/create&#x60; modifications.  The job is asynchronous: poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;. When completed, the response always includes a **preview_url** (rendered PNG) plus the &#x60;template_id&#x60;. Iterate with &#x60;POST /v1/agent/templates/{template_id}/revise&#x60;.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  Creation costs **25 credits**, deducted when the job is queued and fully refunded if the job fails.  ## Canvas  Pass a &#x60;preset&#x60; (instagram-square, instagram-story, og-image, twitter-card, pinterest-pin, square-512) or explicit &#x60;width&#x60; + &#x60;height&#x60; in px.  ## Rate Limits  Standard rate limits apply (60 req/min free, 120 req/min paid).
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAgentTemplateRequest"></param>
        /// <returns>ApiResponse of AgentJobCreatedResponse</returns>
        ApiResponse<AgentJobCreatedResponse> CreateAgentTemplateWithHttpInfo(CreateAgentTemplateRequest createAgentTemplateRequest);
        /// <summary>
        /// Get authoring-agent job status
        /// </summary>
        /// <remarks>
        /// Poll the status of an authoring-agent job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued | | &#x60;processing&#x60; | The agent is authoring (typically 30s-3min) | | &#x60;completed&#x60; | Done — &#x60;template_id&#x60; and &#x60;preview_url&#x60; are set | | &#x60;failed&#x60; | Job failed (see error_message); credits were refunded |  Poll every 2-5 seconds. A job stuck in &#x60;processing&#x60; for more than 10 minutes is failed automatically and its credits refunded.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">Job UUID</param>
        /// <returns>AgentJobStatusResponse</returns>
        AgentJobStatusResponse GetAgentJob(string jobId);

        /// <summary>
        /// Get authoring-agent job status
        /// </summary>
        /// <remarks>
        /// Poll the status of an authoring-agent job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued | | &#x60;processing&#x60; | The agent is authoring (typically 30s-3min) | | &#x60;completed&#x60; | Done — &#x60;template_id&#x60; and &#x60;preview_url&#x60; are set | | &#x60;failed&#x60; | Job failed (see error_message); credits were refunded |  Poll every 2-5 seconds. A job stuck in &#x60;processing&#x60; for more than 10 minutes is failed automatically and its credits refunded.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">Job UUID</param>
        /// <returns>ApiResponse of AgentJobStatusResponse</returns>
        ApiResponse<AgentJobStatusResponse> GetAgentJobWithHttpInfo(string jobId);
        /// <summary>
        /// Revise a template with the authoring agent
        /// </summary>
        /// <remarks>
        /// Send natural-language feedback on an existing image template; the agent revises the draft while keeping layer names stable. Asynchronous — poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;; the completed job always includes a fresh **preview_url**.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  A revision costs **10 credits**, deducted when the job is queued and fully refunded if the job fails.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateId">Template short ID (12 characters)</param>
        /// <param name="reviseAgentTemplateRequest"></param>
        /// <returns>AgentJobCreatedResponse</returns>
        AgentJobCreatedResponse ReviseAgentTemplate(string templateId, ReviseAgentTemplateRequest reviseAgentTemplateRequest);

        /// <summary>
        /// Revise a template with the authoring agent
        /// </summary>
        /// <remarks>
        /// Send natural-language feedback on an existing image template; the agent revises the draft while keeping layer names stable. Asynchronous — poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;; the completed job always includes a fresh **preview_url**.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  A revision costs **10 credits**, deducted when the job is queued and fully refunded if the job fails.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateId">Template short ID (12 characters)</param>
        /// <param name="reviseAgentTemplateRequest"></param>
        /// <returns>ApiResponse of AgentJobCreatedResponse</returns>
        ApiResponse<AgentJobCreatedResponse> ReviseAgentTemplateWithHttpInfo(string templateId, ReviseAgentTemplateRequest reviseAgentTemplateRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAgentApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create a template with the authoring agent
        /// </summary>
        /// <remarks>
        /// Describe the image template you want; the TemplateFox agent authors it for you — valid HTML that renders deterministically AND stays editable in the visual editor, with every layer named and drivable through &#x60;/v1/image/create&#x60; modifications.  The job is asynchronous: poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;. When completed, the response always includes a **preview_url** (rendered PNG) plus the &#x60;template_id&#x60;. Iterate with &#x60;POST /v1/agent/templates/{template_id}/revise&#x60;.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  Creation costs **25 credits**, deducted when the job is queued and fully refunded if the job fails.  ## Canvas  Pass a &#x60;preset&#x60; (instagram-square, instagram-story, og-image, twitter-card, pinterest-pin, square-512) or explicit &#x60;width&#x60; + &#x60;height&#x60; in px.  ## Rate Limits  Standard rate limits apply (60 req/min free, 120 req/min paid).
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAgentTemplateRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AgentJobCreatedResponse</returns>
        System.Threading.Tasks.Task<AgentJobCreatedResponse> CreateAgentTemplateAsync(CreateAgentTemplateRequest createAgentTemplateRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create a template with the authoring agent
        /// </summary>
        /// <remarks>
        /// Describe the image template you want; the TemplateFox agent authors it for you — valid HTML that renders deterministically AND stays editable in the visual editor, with every layer named and drivable through &#x60;/v1/image/create&#x60; modifications.  The job is asynchronous: poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;. When completed, the response always includes a **preview_url** (rendered PNG) plus the &#x60;template_id&#x60;. Iterate with &#x60;POST /v1/agent/templates/{template_id}/revise&#x60;.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  Creation costs **25 credits**, deducted when the job is queued and fully refunded if the job fails.  ## Canvas  Pass a &#x60;preset&#x60; (instagram-square, instagram-story, og-image, twitter-card, pinterest-pin, square-512) or explicit &#x60;width&#x60; + &#x60;height&#x60; in px.  ## Rate Limits  Standard rate limits apply (60 req/min free, 120 req/min paid).
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAgentTemplateRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AgentJobCreatedResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AgentJobCreatedResponse>> CreateAgentTemplateWithHttpInfoAsync(CreateAgentTemplateRequest createAgentTemplateRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get authoring-agent job status
        /// </summary>
        /// <remarks>
        /// Poll the status of an authoring-agent job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued | | &#x60;processing&#x60; | The agent is authoring (typically 30s-3min) | | &#x60;completed&#x60; | Done — &#x60;template_id&#x60; and &#x60;preview_url&#x60; are set | | &#x60;failed&#x60; | Job failed (see error_message); credits were refunded |  Poll every 2-5 seconds. A job stuck in &#x60;processing&#x60; for more than 10 minutes is failed automatically and its credits refunded.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">Job UUID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AgentJobStatusResponse</returns>
        System.Threading.Tasks.Task<AgentJobStatusResponse> GetAgentJobAsync(string jobId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get authoring-agent job status
        /// </summary>
        /// <remarks>
        /// Poll the status of an authoring-agent job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued | | &#x60;processing&#x60; | The agent is authoring (typically 30s-3min) | | &#x60;completed&#x60; | Done — &#x60;template_id&#x60; and &#x60;preview_url&#x60; are set | | &#x60;failed&#x60; | Job failed (see error_message); credits were refunded |  Poll every 2-5 seconds. A job stuck in &#x60;processing&#x60; for more than 10 minutes is failed automatically and its credits refunded.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">Job UUID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AgentJobStatusResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AgentJobStatusResponse>> GetAgentJobWithHttpInfoAsync(string jobId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Revise a template with the authoring agent
        /// </summary>
        /// <remarks>
        /// Send natural-language feedback on an existing image template; the agent revises the draft while keeping layer names stable. Asynchronous — poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;; the completed job always includes a fresh **preview_url**.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  A revision costs **10 credits**, deducted when the job is queued and fully refunded if the job fails.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateId">Template short ID (12 characters)</param>
        /// <param name="reviseAgentTemplateRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AgentJobCreatedResponse</returns>
        System.Threading.Tasks.Task<AgentJobCreatedResponse> ReviseAgentTemplateAsync(string templateId, ReviseAgentTemplateRequest reviseAgentTemplateRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Revise a template with the authoring agent
        /// </summary>
        /// <remarks>
        /// Send natural-language feedback on an existing image template; the agent revises the draft while keeping layer names stable. Asynchronous — poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;; the completed job always includes a fresh **preview_url**.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  A revision costs **10 credits**, deducted when the job is queued and fully refunded if the job fails.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateId">Template short ID (12 characters)</param>
        /// <param name="reviseAgentTemplateRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AgentJobCreatedResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AgentJobCreatedResponse>> ReviseAgentTemplateWithHttpInfoAsync(string templateId, ReviseAgentTemplateRequest reviseAgentTemplateRequest, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAgentApi : IAgentApiSync, IAgentApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AgentApi : IDisposable, IAgentApi
    {
        private TemplateFox.SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public AgentApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public AgentApi(string basePath)
        {
            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                new TemplateFox.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public AgentApi(TemplateFox.SDK.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AgentApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AgentApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                new TemplateFox.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AgentApi(HttpClient client, TemplateFox.SDK.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public AgentApi(TemplateFox.SDK.Client.ISynchronousClient client, TemplateFox.SDK.Client.IAsynchronousClient asyncClient, TemplateFox.SDK.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public TemplateFox.SDK.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public TemplateFox.SDK.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public TemplateFox.SDK.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public TemplateFox.SDK.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public TemplateFox.SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create a template with the authoring agent Describe the image template you want; the TemplateFox agent authors it for you — valid HTML that renders deterministically AND stays editable in the visual editor, with every layer named and drivable through &#x60;/v1/image/create&#x60; modifications.  The job is asynchronous: poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;. When completed, the response always includes a **preview_url** (rendered PNG) plus the &#x60;template_id&#x60;. Iterate with &#x60;POST /v1/agent/templates/{template_id}/revise&#x60;.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  Creation costs **25 credits**, deducted when the job is queued and fully refunded if the job fails.  ## Canvas  Pass a &#x60;preset&#x60; (instagram-square, instagram-story, og-image, twitter-card, pinterest-pin, square-512) or explicit &#x60;width&#x60; + &#x60;height&#x60; in px.  ## Rate Limits  Standard rate limits apply (60 req/min free, 120 req/min paid).
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAgentTemplateRequest"></param>
        /// <returns>AgentJobCreatedResponse</returns>
        public AgentJobCreatedResponse CreateAgentTemplate(CreateAgentTemplateRequest createAgentTemplateRequest)
        {
            TemplateFox.SDK.Client.ApiResponse<AgentJobCreatedResponse> localVarResponse = CreateAgentTemplateWithHttpInfo(createAgentTemplateRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a template with the authoring agent Describe the image template you want; the TemplateFox agent authors it for you — valid HTML that renders deterministically AND stays editable in the visual editor, with every layer named and drivable through &#x60;/v1/image/create&#x60; modifications.  The job is asynchronous: poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;. When completed, the response always includes a **preview_url** (rendered PNG) plus the &#x60;template_id&#x60;. Iterate with &#x60;POST /v1/agent/templates/{template_id}/revise&#x60;.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  Creation costs **25 credits**, deducted when the job is queued and fully refunded if the job fails.  ## Canvas  Pass a &#x60;preset&#x60; (instagram-square, instagram-story, og-image, twitter-card, pinterest-pin, square-512) or explicit &#x60;width&#x60; + &#x60;height&#x60; in px.  ## Rate Limits  Standard rate limits apply (60 req/min free, 120 req/min paid).
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAgentTemplateRequest"></param>
        /// <returns>ApiResponse of AgentJobCreatedResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<AgentJobCreatedResponse> CreateAgentTemplateWithHttpInfo(CreateAgentTemplateRequest createAgentTemplateRequest)
        {
            // verify the required parameter 'createAgentTemplateRequest' is set
            if (createAgentTemplateRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'createAgentTemplateRequest' when calling AgentApi->CreateAgentTemplate");

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createAgentTemplateRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<AgentJobCreatedResponse>("/v1/agent/templates", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateAgentTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a template with the authoring agent Describe the image template you want; the TemplateFox agent authors it for you — valid HTML that renders deterministically AND stays editable in the visual editor, with every layer named and drivable through &#x60;/v1/image/create&#x60; modifications.  The job is asynchronous: poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;. When completed, the response always includes a **preview_url** (rendered PNG) plus the &#x60;template_id&#x60;. Iterate with &#x60;POST /v1/agent/templates/{template_id}/revise&#x60;.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  Creation costs **25 credits**, deducted when the job is queued and fully refunded if the job fails.  ## Canvas  Pass a &#x60;preset&#x60; (instagram-square, instagram-story, og-image, twitter-card, pinterest-pin, square-512) or explicit &#x60;width&#x60; + &#x60;height&#x60; in px.  ## Rate Limits  Standard rate limits apply (60 req/min free, 120 req/min paid).
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAgentTemplateRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AgentJobCreatedResponse</returns>
        public async System.Threading.Tasks.Task<AgentJobCreatedResponse> CreateAgentTemplateAsync(CreateAgentTemplateRequest createAgentTemplateRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<AgentJobCreatedResponse> localVarResponse = await CreateAgentTemplateWithHttpInfoAsync(createAgentTemplateRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a template with the authoring agent Describe the image template you want; the TemplateFox agent authors it for you — valid HTML that renders deterministically AND stays editable in the visual editor, with every layer named and drivable through &#x60;/v1/image/create&#x60; modifications.  The job is asynchronous: poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;. When completed, the response always includes a **preview_url** (rendered PNG) plus the &#x60;template_id&#x60;. Iterate with &#x60;POST /v1/agent/templates/{template_id}/revise&#x60;.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  Creation costs **25 credits**, deducted when the job is queued and fully refunded if the job fails.  ## Canvas  Pass a &#x60;preset&#x60; (instagram-square, instagram-story, og-image, twitter-card, pinterest-pin, square-512) or explicit &#x60;width&#x60; + &#x60;height&#x60; in px.  ## Rate Limits  Standard rate limits apply (60 req/min free, 120 req/min paid).
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAgentTemplateRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AgentJobCreatedResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<AgentJobCreatedResponse>> CreateAgentTemplateWithHttpInfoAsync(CreateAgentTemplateRequest createAgentTemplateRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createAgentTemplateRequest' is set
            if (createAgentTemplateRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'createAgentTemplateRequest' when calling AgentApi->CreateAgentTemplate");


            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createAgentTemplateRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<AgentJobCreatedResponse>("/v1/agent/templates", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateAgentTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get authoring-agent job status Poll the status of an authoring-agent job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued | | &#x60;processing&#x60; | The agent is authoring (typically 30s-3min) | | &#x60;completed&#x60; | Done — &#x60;template_id&#x60; and &#x60;preview_url&#x60; are set | | &#x60;failed&#x60; | Job failed (see error_message); credits were refunded |  Poll every 2-5 seconds. A job stuck in &#x60;processing&#x60; for more than 10 minutes is failed automatically and its credits refunded.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">Job UUID</param>
        /// <returns>AgentJobStatusResponse</returns>
        public AgentJobStatusResponse GetAgentJob(string jobId)
        {
            TemplateFox.SDK.Client.ApiResponse<AgentJobStatusResponse> localVarResponse = GetAgentJobWithHttpInfo(jobId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get authoring-agent job status Poll the status of an authoring-agent job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued | | &#x60;processing&#x60; | The agent is authoring (typically 30s-3min) | | &#x60;completed&#x60; | Done — &#x60;template_id&#x60; and &#x60;preview_url&#x60; are set | | &#x60;failed&#x60; | Job failed (see error_message); credits were refunded |  Poll every 2-5 seconds. A job stuck in &#x60;processing&#x60; for more than 10 minutes is failed automatically and its credits refunded.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">Job UUID</param>
        /// <returns>ApiResponse of AgentJobStatusResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<AgentJobStatusResponse> GetAgentJobWithHttpInfo(string jobId)
        {
            // verify the required parameter 'jobId' is set
            if (jobId == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'jobId' when calling AgentApi->GetAgentJob");

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("job_id", TemplateFox.SDK.Client.ClientUtils.ParameterToString(jobId)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<AgentJobStatusResponse>("/v1/agent/jobs/{job_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAgentJob", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get authoring-agent job status Poll the status of an authoring-agent job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued | | &#x60;processing&#x60; | The agent is authoring (typically 30s-3min) | | &#x60;completed&#x60; | Done — &#x60;template_id&#x60; and &#x60;preview_url&#x60; are set | | &#x60;failed&#x60; | Job failed (see error_message); credits were refunded |  Poll every 2-5 seconds. A job stuck in &#x60;processing&#x60; for more than 10 minutes is failed automatically and its credits refunded.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">Job UUID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AgentJobStatusResponse</returns>
        public async System.Threading.Tasks.Task<AgentJobStatusResponse> GetAgentJobAsync(string jobId, System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<AgentJobStatusResponse> localVarResponse = await GetAgentJobWithHttpInfoAsync(jobId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get authoring-agent job status Poll the status of an authoring-agent job.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Status Values  | Status | Description | |- -- -- -- -|- -- -- -- -- -- --| | &#x60;pending&#x60; | Job is queued | | &#x60;processing&#x60; | The agent is authoring (typically 30s-3min) | | &#x60;completed&#x60; | Done — &#x60;template_id&#x60; and &#x60;preview_url&#x60; are set | | &#x60;failed&#x60; | Job failed (see error_message); credits were refunded |  Poll every 2-5 seconds. A job stuck in &#x60;processing&#x60; for more than 10 minutes is failed automatically and its credits refunded.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">Job UUID</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AgentJobStatusResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<AgentJobStatusResponse>> GetAgentJobWithHttpInfoAsync(string jobId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'jobId' is set
            if (jobId == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'jobId' when calling AgentApi->GetAgentJob");


            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("job_id", TemplateFox.SDK.Client.ClientUtils.ParameterToString(jobId)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<AgentJobStatusResponse>("/v1/agent/jobs/{job_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAgentJob", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revise a template with the authoring agent Send natural-language feedback on an existing image template; the agent revises the draft while keeping layer names stable. Asynchronous — poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;; the completed job always includes a fresh **preview_url**.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  A revision costs **10 credits**, deducted when the job is queued and fully refunded if the job fails.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateId">Template short ID (12 characters)</param>
        /// <param name="reviseAgentTemplateRequest"></param>
        /// <returns>AgentJobCreatedResponse</returns>
        public AgentJobCreatedResponse ReviseAgentTemplate(string templateId, ReviseAgentTemplateRequest reviseAgentTemplateRequest)
        {
            TemplateFox.SDK.Client.ApiResponse<AgentJobCreatedResponse> localVarResponse = ReviseAgentTemplateWithHttpInfo(templateId, reviseAgentTemplateRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Revise a template with the authoring agent Send natural-language feedback on an existing image template; the agent revises the draft while keeping layer names stable. Asynchronous — poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;; the completed job always includes a fresh **preview_url**.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  A revision costs **10 credits**, deducted when the job is queued and fully refunded if the job fails.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateId">Template short ID (12 characters)</param>
        /// <param name="reviseAgentTemplateRequest"></param>
        /// <returns>ApiResponse of AgentJobCreatedResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<AgentJobCreatedResponse> ReviseAgentTemplateWithHttpInfo(string templateId, ReviseAgentTemplateRequest reviseAgentTemplateRequest)
        {
            // verify the required parameter 'templateId' is set
            if (templateId == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'templateId' when calling AgentApi->ReviseAgentTemplate");

            // verify the required parameter 'reviseAgentTemplateRequest' is set
            if (reviseAgentTemplateRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'reviseAgentTemplateRequest' when calling AgentApi->ReviseAgentTemplate");

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("template_id", TemplateFox.SDK.Client.ClientUtils.ParameterToString(templateId)); // path parameter
            localVarRequestOptions.Data = reviseAgentTemplateRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<AgentJobCreatedResponse>("/v1/agent/templates/{template_id}/revise", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReviseAgentTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Revise a template with the authoring agent Send natural-language feedback on an existing image template; the agent revises the draft while keeping layer names stable. Asynchronous — poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;; the completed job always includes a fresh **preview_url**.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  A revision costs **10 credits**, deducted when the job is queued and fully refunded if the job fails.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateId">Template short ID (12 characters)</param>
        /// <param name="reviseAgentTemplateRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AgentJobCreatedResponse</returns>
        public async System.Threading.Tasks.Task<AgentJobCreatedResponse> ReviseAgentTemplateAsync(string templateId, ReviseAgentTemplateRequest reviseAgentTemplateRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<AgentJobCreatedResponse> localVarResponse = await ReviseAgentTemplateWithHttpInfoAsync(templateId, reviseAgentTemplateRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Revise a template with the authoring agent Send natural-language feedback on an existing image template; the agent revises the draft while keeping layer names stable. Asynchronous — poll &#x60;GET /v1/agent/jobs/{job_id}&#x60;; the completed job always includes a fresh **preview_url**.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Credits  A revision costs **10 credits**, deducted when the job is queued and fully refunded if the job fails.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="templateId">Template short ID (12 characters)</param>
        /// <param name="reviseAgentTemplateRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AgentJobCreatedResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<AgentJobCreatedResponse>> ReviseAgentTemplateWithHttpInfoAsync(string templateId, ReviseAgentTemplateRequest reviseAgentTemplateRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'templateId' is set
            if (templateId == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'templateId' when calling AgentApi->ReviseAgentTemplate");

            // verify the required parameter 'reviseAgentTemplateRequest' is set
            if (reviseAgentTemplateRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'reviseAgentTemplateRequest' when calling AgentApi->ReviseAgentTemplate");


            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("template_id", TemplateFox.SDK.Client.ClientUtils.ParameterToString(templateId)); // path parameter
            localVarRequestOptions.Data = reviseAgentTemplateRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<AgentJobCreatedResponse>("/v1/agent/templates/{template_id}/revise", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ReviseAgentTemplate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
