/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using TemplateFox.SDK.Client;
using TemplateFox.SDK.Model;

namespace TemplateFox.SDK.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IImageApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Generate image from template
        /// </summary>
        /// <remarks>
        /// Generate an image (PNG, JPEG or WebP) from an image template.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Request Body  | Field | Type | Required | Description | |- -- -- --|- -- -- -|- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;template_id&#x60; | string | ✅ Yes | Template short ID (12 characters) | | &#x60;modifications&#x60; | array | No | Modify elements by layer name (see below) | | &#x60;format&#x60; | string | No | &#x60;png&#x60; (default), &#x60;jpeg&#x60; or &#x60;webp&#x60; | | &#x60;width&#x60; | integer | No | Output width in pixels (defaults to the template&#39;s native width) | | &#x60;export_type&#x60; | string | No | &#x60;url&#x60; (default) or &#x60;binary&#x60; |  ## Modifications  Each modification targets a layer by the &#x60;name&#x60; you set in the editor&#39;s Layers panel:  | Property | Description | |- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;name&#x60; | Layer name to modify (required) | | &#x60;text&#x60; | Replace the layer&#39;s text | | &#x60;image_url&#x60; | Set the layer&#39;s image (&#x60;src&#x60; for images, &#x60;background-image&#x60; otherwise) | | &#x60;color&#x60; | Text color | | &#x60;background&#x60; | Background color | | &#x60;hidden&#x60; | Hide (&#x60;true&#x60;) or show (&#x60;false&#x60;) the layer |  Unknown layer names are skipped and listed in the response &#x60;warnings&#x60;. A name that matches several layers is applied to all of them.  ## Export Types - &#x60;url&#x60; (default): image is uploaded to CDN, returns JSON with URL - &#x60;binary&#x60;: returns raw image bytes directly  **Note:** This endpoint only accepts image templates. Use &#x60;/v1/pdf/create&#x60; for PDF templates.  **Credits:** 1 credit deducted per successful generation.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createImageRequest"></param>
        /// <returns>CreateImageResponse</returns>
        CreateImageResponse CreateImage(CreateImageRequest createImageRequest);

        /// <summary>
        /// Generate image from template
        /// </summary>
        /// <remarks>
        /// Generate an image (PNG, JPEG or WebP) from an image template.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Request Body  | Field | Type | Required | Description | |- -- -- --|- -- -- -|- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;template_id&#x60; | string | ✅ Yes | Template short ID (12 characters) | | &#x60;modifications&#x60; | array | No | Modify elements by layer name (see below) | | &#x60;format&#x60; | string | No | &#x60;png&#x60; (default), &#x60;jpeg&#x60; or &#x60;webp&#x60; | | &#x60;width&#x60; | integer | No | Output width in pixels (defaults to the template&#39;s native width) | | &#x60;export_type&#x60; | string | No | &#x60;url&#x60; (default) or &#x60;binary&#x60; |  ## Modifications  Each modification targets a layer by the &#x60;name&#x60; you set in the editor&#39;s Layers panel:  | Property | Description | |- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;name&#x60; | Layer name to modify (required) | | &#x60;text&#x60; | Replace the layer&#39;s text | | &#x60;image_url&#x60; | Set the layer&#39;s image (&#x60;src&#x60; for images, &#x60;background-image&#x60; otherwise) | | &#x60;color&#x60; | Text color | | &#x60;background&#x60; | Background color | | &#x60;hidden&#x60; | Hide (&#x60;true&#x60;) or show (&#x60;false&#x60;) the layer |  Unknown layer names are skipped and listed in the response &#x60;warnings&#x60;. A name that matches several layers is applied to all of them.  ## Export Types - &#x60;url&#x60; (default): image is uploaded to CDN, returns JSON with URL - &#x60;binary&#x60;: returns raw image bytes directly  **Note:** This endpoint only accepts image templates. Use &#x60;/v1/pdf/create&#x60; for PDF templates.  **Credits:** 1 credit deducted per successful generation.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createImageRequest"></param>
        /// <returns>ApiResponse of CreateImageResponse</returns>
        ApiResponse<CreateImageResponse> CreateImageWithHttpInfo(CreateImageRequest createImageRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IImageApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Generate image from template
        /// </summary>
        /// <remarks>
        /// Generate an image (PNG, JPEG or WebP) from an image template.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Request Body  | Field | Type | Required | Description | |- -- -- --|- -- -- -|- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;template_id&#x60; | string | ✅ Yes | Template short ID (12 characters) | | &#x60;modifications&#x60; | array | No | Modify elements by layer name (see below) | | &#x60;format&#x60; | string | No | &#x60;png&#x60; (default), &#x60;jpeg&#x60; or &#x60;webp&#x60; | | &#x60;width&#x60; | integer | No | Output width in pixels (defaults to the template&#39;s native width) | | &#x60;export_type&#x60; | string | No | &#x60;url&#x60; (default) or &#x60;binary&#x60; |  ## Modifications  Each modification targets a layer by the &#x60;name&#x60; you set in the editor&#39;s Layers panel:  | Property | Description | |- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;name&#x60; | Layer name to modify (required) | | &#x60;text&#x60; | Replace the layer&#39;s text | | &#x60;image_url&#x60; | Set the layer&#39;s image (&#x60;src&#x60; for images, &#x60;background-image&#x60; otherwise) | | &#x60;color&#x60; | Text color | | &#x60;background&#x60; | Background color | | &#x60;hidden&#x60; | Hide (&#x60;true&#x60;) or show (&#x60;false&#x60;) the layer |  Unknown layer names are skipped and listed in the response &#x60;warnings&#x60;. A name that matches several layers is applied to all of them.  ## Export Types - &#x60;url&#x60; (default): image is uploaded to CDN, returns JSON with URL - &#x60;binary&#x60;: returns raw image bytes directly  **Note:** This endpoint only accepts image templates. Use &#x60;/v1/pdf/create&#x60; for PDF templates.  **Credits:** 1 credit deducted per successful generation.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createImageRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateImageResponse</returns>
        System.Threading.Tasks.Task<CreateImageResponse> CreateImageAsync(CreateImageRequest createImageRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Generate image from template
        /// </summary>
        /// <remarks>
        /// Generate an image (PNG, JPEG or WebP) from an image template.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Request Body  | Field | Type | Required | Description | |- -- -- --|- -- -- -|- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;template_id&#x60; | string | ✅ Yes | Template short ID (12 characters) | | &#x60;modifications&#x60; | array | No | Modify elements by layer name (see below) | | &#x60;format&#x60; | string | No | &#x60;png&#x60; (default), &#x60;jpeg&#x60; or &#x60;webp&#x60; | | &#x60;width&#x60; | integer | No | Output width in pixels (defaults to the template&#39;s native width) | | &#x60;export_type&#x60; | string | No | &#x60;url&#x60; (default) or &#x60;binary&#x60; |  ## Modifications  Each modification targets a layer by the &#x60;name&#x60; you set in the editor&#39;s Layers panel:  | Property | Description | |- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;name&#x60; | Layer name to modify (required) | | &#x60;text&#x60; | Replace the layer&#39;s text | | &#x60;image_url&#x60; | Set the layer&#39;s image (&#x60;src&#x60; for images, &#x60;background-image&#x60; otherwise) | | &#x60;color&#x60; | Text color | | &#x60;background&#x60; | Background color | | &#x60;hidden&#x60; | Hide (&#x60;true&#x60;) or show (&#x60;false&#x60;) the layer |  Unknown layer names are skipped and listed in the response &#x60;warnings&#x60;. A name that matches several layers is applied to all of them.  ## Export Types - &#x60;url&#x60; (default): image is uploaded to CDN, returns JSON with URL - &#x60;binary&#x60;: returns raw image bytes directly  **Note:** This endpoint only accepts image templates. Use &#x60;/v1/pdf/create&#x60; for PDF templates.  **Credits:** 1 credit deducted per successful generation.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createImageRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateImageResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateImageResponse>> CreateImageWithHttpInfoAsync(CreateImageRequest createImageRequest, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IImageApi : IImageApiSync, IImageApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ImageApi : IDisposable, IImageApi
    {
        private TemplateFox.SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ImageApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ImageApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImageApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ImageApi(string basePath)
        {
            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                new TemplateFox.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImageApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ImageApi(TemplateFox.SDK.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImageApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ImageApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImageApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ImageApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                new TemplateFox.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImageApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ImageApi(HttpClient client, TemplateFox.SDK.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImageApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ImageApi(TemplateFox.SDK.Client.ISynchronousClient client, TemplateFox.SDK.Client.IAsynchronousClient asyncClient, TemplateFox.SDK.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public TemplateFox.SDK.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public TemplateFox.SDK.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public TemplateFox.SDK.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public TemplateFox.SDK.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public TemplateFox.SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Generate image from template Generate an image (PNG, JPEG or WebP) from an image template.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Request Body  | Field | Type | Required | Description | |- -- -- --|- -- -- -|- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;template_id&#x60; | string | ✅ Yes | Template short ID (12 characters) | | &#x60;modifications&#x60; | array | No | Modify elements by layer name (see below) | | &#x60;format&#x60; | string | No | &#x60;png&#x60; (default), &#x60;jpeg&#x60; or &#x60;webp&#x60; | | &#x60;width&#x60; | integer | No | Output width in pixels (defaults to the template&#39;s native width) | | &#x60;export_type&#x60; | string | No | &#x60;url&#x60; (default) or &#x60;binary&#x60; |  ## Modifications  Each modification targets a layer by the &#x60;name&#x60; you set in the editor&#39;s Layers panel:  | Property | Description | |- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;name&#x60; | Layer name to modify (required) | | &#x60;text&#x60; | Replace the layer&#39;s text | | &#x60;image_url&#x60; | Set the layer&#39;s image (&#x60;src&#x60; for images, &#x60;background-image&#x60; otherwise) | | &#x60;color&#x60; | Text color | | &#x60;background&#x60; | Background color | | &#x60;hidden&#x60; | Hide (&#x60;true&#x60;) or show (&#x60;false&#x60;) the layer |  Unknown layer names are skipped and listed in the response &#x60;warnings&#x60;. A name that matches several layers is applied to all of them.  ## Export Types - &#x60;url&#x60; (default): image is uploaded to CDN, returns JSON with URL - &#x60;binary&#x60;: returns raw image bytes directly  **Note:** This endpoint only accepts image templates. Use &#x60;/v1/pdf/create&#x60; for PDF templates.  **Credits:** 1 credit deducted per successful generation.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createImageRequest"></param>
        /// <returns>CreateImageResponse</returns>
        public CreateImageResponse CreateImage(CreateImageRequest createImageRequest)
        {
            TemplateFox.SDK.Client.ApiResponse<CreateImageResponse> localVarResponse = CreateImageWithHttpInfo(createImageRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Generate image from template Generate an image (PNG, JPEG or WebP) from an image template.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Request Body  | Field | Type | Required | Description | |- -- -- --|- -- -- -|- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;template_id&#x60; | string | ✅ Yes | Template short ID (12 characters) | | &#x60;modifications&#x60; | array | No | Modify elements by layer name (see below) | | &#x60;format&#x60; | string | No | &#x60;png&#x60; (default), &#x60;jpeg&#x60; or &#x60;webp&#x60; | | &#x60;width&#x60; | integer | No | Output width in pixels (defaults to the template&#39;s native width) | | &#x60;export_type&#x60; | string | No | &#x60;url&#x60; (default) or &#x60;binary&#x60; |  ## Modifications  Each modification targets a layer by the &#x60;name&#x60; you set in the editor&#39;s Layers panel:  | Property | Description | |- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;name&#x60; | Layer name to modify (required) | | &#x60;text&#x60; | Replace the layer&#39;s text | | &#x60;image_url&#x60; | Set the layer&#39;s image (&#x60;src&#x60; for images, &#x60;background-image&#x60; otherwise) | | &#x60;color&#x60; | Text color | | &#x60;background&#x60; | Background color | | &#x60;hidden&#x60; | Hide (&#x60;true&#x60;) or show (&#x60;false&#x60;) the layer |  Unknown layer names are skipped and listed in the response &#x60;warnings&#x60;. A name that matches several layers is applied to all of them.  ## Export Types - &#x60;url&#x60; (default): image is uploaded to CDN, returns JSON with URL - &#x60;binary&#x60;: returns raw image bytes directly  **Note:** This endpoint only accepts image templates. Use &#x60;/v1/pdf/create&#x60; for PDF templates.  **Credits:** 1 credit deducted per successful generation.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createImageRequest"></param>
        /// <returns>ApiResponse of CreateImageResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<CreateImageResponse> CreateImageWithHttpInfo(CreateImageRequest createImageRequest)
        {
            // verify the required parameter 'createImageRequest' is set
            if (createImageRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'createImageRequest' when calling ImageApi->CreateImage");

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "image/png"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createImageRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreateImageResponse>("/v1/image/create", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateImage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Generate image from template Generate an image (PNG, JPEG or WebP) from an image template.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Request Body  | Field | Type | Required | Description | |- -- -- --|- -- -- -|- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;template_id&#x60; | string | ✅ Yes | Template short ID (12 characters) | | &#x60;modifications&#x60; | array | No | Modify elements by layer name (see below) | | &#x60;format&#x60; | string | No | &#x60;png&#x60; (default), &#x60;jpeg&#x60; or &#x60;webp&#x60; | | &#x60;width&#x60; | integer | No | Output width in pixels (defaults to the template&#39;s native width) | | &#x60;export_type&#x60; | string | No | &#x60;url&#x60; (default) or &#x60;binary&#x60; |  ## Modifications  Each modification targets a layer by the &#x60;name&#x60; you set in the editor&#39;s Layers panel:  | Property | Description | |- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;name&#x60; | Layer name to modify (required) | | &#x60;text&#x60; | Replace the layer&#39;s text | | &#x60;image_url&#x60; | Set the layer&#39;s image (&#x60;src&#x60; for images, &#x60;background-image&#x60; otherwise) | | &#x60;color&#x60; | Text color | | &#x60;background&#x60; | Background color | | &#x60;hidden&#x60; | Hide (&#x60;true&#x60;) or show (&#x60;false&#x60;) the layer |  Unknown layer names are skipped and listed in the response &#x60;warnings&#x60;. A name that matches several layers is applied to all of them.  ## Export Types - &#x60;url&#x60; (default): image is uploaded to CDN, returns JSON with URL - &#x60;binary&#x60;: returns raw image bytes directly  **Note:** This endpoint only accepts image templates. Use &#x60;/v1/pdf/create&#x60; for PDF templates.  **Credits:** 1 credit deducted per successful generation.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createImageRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateImageResponse</returns>
        public async System.Threading.Tasks.Task<CreateImageResponse> CreateImageAsync(CreateImageRequest createImageRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<CreateImageResponse> localVarResponse = await CreateImageWithHttpInfoAsync(createImageRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Generate image from template Generate an image (PNG, JPEG or WebP) from an image template.  **Authentication:** API Key required (&#x60;x-api-key&#x60; header)  ## Request Body  | Field | Type | Required | Description | |- -- -- --|- -- -- -|- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;template_id&#x60; | string | ✅ Yes | Template short ID (12 characters) | | &#x60;modifications&#x60; | array | No | Modify elements by layer name (see below) | | &#x60;format&#x60; | string | No | &#x60;png&#x60; (default), &#x60;jpeg&#x60; or &#x60;webp&#x60; | | &#x60;width&#x60; | integer | No | Output width in pixels (defaults to the template&#39;s native width) | | &#x60;export_type&#x60; | string | No | &#x60;url&#x60; (default) or &#x60;binary&#x60; |  ## Modifications  Each modification targets a layer by the &#x60;name&#x60; you set in the editor&#39;s Layers panel:  | Property | Description | |- -- -- -- -- -|- -- -- -- -- -- --| | &#x60;name&#x60; | Layer name to modify (required) | | &#x60;text&#x60; | Replace the layer&#39;s text | | &#x60;image_url&#x60; | Set the layer&#39;s image (&#x60;src&#x60; for images, &#x60;background-image&#x60; otherwise) | | &#x60;color&#x60; | Text color | | &#x60;background&#x60; | Background color | | &#x60;hidden&#x60; | Hide (&#x60;true&#x60;) or show (&#x60;false&#x60;) the layer |  Unknown layer names are skipped and listed in the response &#x60;warnings&#x60;. A name that matches several layers is applied to all of them.  ## Export Types - &#x60;url&#x60; (default): image is uploaded to CDN, returns JSON with URL - &#x60;binary&#x60;: returns raw image bytes directly  **Note:** This endpoint only accepts image templates. Use &#x60;/v1/pdf/create&#x60; for PDF templates.  **Credits:** 1 credit deducted per successful generation.  **Rate Limits:** 60 requests/min (free), 120 requests/min (paid). Headers included in response.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createImageRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateImageResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<CreateImageResponse>> CreateImageWithHttpInfoAsync(CreateImageRequest createImageRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createImageRequest' is set
            if (createImageRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'createImageRequest' when calling ImageApi->CreateImage");


            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "image/png"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createImageRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CreateImageResponse>("/v1/image/create", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateImage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
