/*
 * TemplateFox API
 *
 * Generate beautiful PDFs from HTML/CSS templates with Jinja2 via API. Design once, generate thousands.
 *
 * The version of the OpenAPI document: 1.10.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using TemplateFox.SDK.Client;
using TemplateFox.SDK.Model;

namespace TemplateFox.SDK.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPDFToolsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Extract pages from a PDF
        /// </summary>
        /// <remarks>
        /// Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (&#x60;1-3&#x60;) and singles (&#x60;5&#x60;). Order is preserved: &#x60;5,1,3&#x60; outputs those 3 pages in that order.  **Credits:** 1 credit per call.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="extractPdfPagesRequest"></param>
        /// <returns>PdfToolsResponse</returns>
        PdfToolsResponse ExtractPdfPages(ExtractPdfPagesRequest extractPdfPagesRequest);

        /// <summary>
        /// Extract pages from a PDF
        /// </summary>
        /// <remarks>
        /// Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (&#x60;1-3&#x60;) and singles (&#x60;5&#x60;). Order is preserved: &#x60;5,1,3&#x60; outputs those 3 pages in that order.  **Credits:** 1 credit per call.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="extractPdfPagesRequest"></param>
        /// <returns>ApiResponse of PdfToolsResponse</returns>
        ApiResponse<PdfToolsResponse> ExtractPdfPagesWithHttpInfo(ExtractPdfPagesRequest extractPdfPagesRequest);
        /// <summary>
        /// Merge PDFs
        /// </summary>
        /// <remarks>
        /// Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mergePdfRequest"></param>
        /// <returns>PdfToolsResponse</returns>
        PdfToolsResponse MergePdf(MergePdfRequest mergePdfRequest);

        /// <summary>
        /// Merge PDFs
        /// </summary>
        /// <remarks>
        /// Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mergePdfRequest"></param>
        /// <returns>ApiResponse of PdfToolsResponse</returns>
        ApiResponse<PdfToolsResponse> MergePdfWithHttpInfo(MergePdfRequest mergePdfRequest);
        /// <summary>
        /// Rotate pages of a PDF
        /// </summary>
        /// <remarks>
        /// Rotate every page by the same angle (&#x60;rotation&#x60;), or apply a per-page rotation map (&#x60;page_rotations&#x60;). Rotations are cumulative with the page&#39;s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rotatePdfRequest"></param>
        /// <returns>PdfToolsResponse</returns>
        PdfToolsResponse RotatePdf(RotatePdfRequest rotatePdfRequest);

        /// <summary>
        /// Rotate pages of a PDF
        /// </summary>
        /// <remarks>
        /// Rotate every page by the same angle (&#x60;rotation&#x60;), or apply a per-page rotation map (&#x60;page_rotations&#x60;). Rotations are cumulative with the page&#39;s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rotatePdfRequest"></param>
        /// <returns>ApiResponse of PdfToolsResponse</returns>
        ApiResponse<PdfToolsResponse> RotatePdfWithHttpInfo(RotatePdfRequest rotatePdfRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPDFToolsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Extract pages from a PDF
        /// </summary>
        /// <remarks>
        /// Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (&#x60;1-3&#x60;) and singles (&#x60;5&#x60;). Order is preserved: &#x60;5,1,3&#x60; outputs those 3 pages in that order.  **Credits:** 1 credit per call.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="extractPdfPagesRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PdfToolsResponse</returns>
        System.Threading.Tasks.Task<PdfToolsResponse> ExtractPdfPagesAsync(ExtractPdfPagesRequest extractPdfPagesRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Extract pages from a PDF
        /// </summary>
        /// <remarks>
        /// Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (&#x60;1-3&#x60;) and singles (&#x60;5&#x60;). Order is preserved: &#x60;5,1,3&#x60; outputs those 3 pages in that order.  **Credits:** 1 credit per call.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="extractPdfPagesRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PdfToolsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PdfToolsResponse>> ExtractPdfPagesWithHttpInfoAsync(ExtractPdfPagesRequest extractPdfPagesRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Merge PDFs
        /// </summary>
        /// <remarks>
        /// Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mergePdfRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PdfToolsResponse</returns>
        System.Threading.Tasks.Task<PdfToolsResponse> MergePdfAsync(MergePdfRequest mergePdfRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Merge PDFs
        /// </summary>
        /// <remarks>
        /// Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mergePdfRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PdfToolsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PdfToolsResponse>> MergePdfWithHttpInfoAsync(MergePdfRequest mergePdfRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Rotate pages of a PDF
        /// </summary>
        /// <remarks>
        /// Rotate every page by the same angle (&#x60;rotation&#x60;), or apply a per-page rotation map (&#x60;page_rotations&#x60;). Rotations are cumulative with the page&#39;s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rotatePdfRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PdfToolsResponse</returns>
        System.Threading.Tasks.Task<PdfToolsResponse> RotatePdfAsync(RotatePdfRequest rotatePdfRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Rotate pages of a PDF
        /// </summary>
        /// <remarks>
        /// Rotate every page by the same angle (&#x60;rotation&#x60;), or apply a per-page rotation map (&#x60;page_rotations&#x60;). Rotations are cumulative with the page&#39;s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
        /// </remarks>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rotatePdfRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PdfToolsResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PdfToolsResponse>> RotatePdfWithHttpInfoAsync(RotatePdfRequest rotatePdfRequest, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPDFToolsApi : IPDFToolsApiSync, IPDFToolsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PDFToolsApi : IDisposable, IPDFToolsApi
    {
        private TemplateFox.SDK.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFToolsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public PDFToolsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFToolsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public PDFToolsApi(string basePath)
        {
            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                new TemplateFox.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFToolsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public PDFToolsApi(TemplateFox.SDK.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFToolsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PDFToolsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFToolsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PDFToolsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                new TemplateFox.SDK.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFToolsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public PDFToolsApi(HttpClient client, TemplateFox.SDK.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = TemplateFox.SDK.Client.Configuration.MergeConfigurations(
                TemplateFox.SDK.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new TemplateFox.SDK.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFToolsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public PDFToolsApi(TemplateFox.SDK.Client.ISynchronousClient client, TemplateFox.SDK.Client.IAsynchronousClient asyncClient, TemplateFox.SDK.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = TemplateFox.SDK.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public TemplateFox.SDK.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public TemplateFox.SDK.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public TemplateFox.SDK.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public TemplateFox.SDK.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public TemplateFox.SDK.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Extract pages from a PDF Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (&#x60;1-3&#x60;) and singles (&#x60;5&#x60;). Order is preserved: &#x60;5,1,3&#x60; outputs those 3 pages in that order.  **Credits:** 1 credit per call.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="extractPdfPagesRequest"></param>
        /// <returns>PdfToolsResponse</returns>
        public PdfToolsResponse ExtractPdfPages(ExtractPdfPagesRequest extractPdfPagesRequest)
        {
            TemplateFox.SDK.Client.ApiResponse<PdfToolsResponse> localVarResponse = ExtractPdfPagesWithHttpInfo(extractPdfPagesRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Extract pages from a PDF Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (&#x60;1-3&#x60;) and singles (&#x60;5&#x60;). Order is preserved: &#x60;5,1,3&#x60; outputs those 3 pages in that order.  **Credits:** 1 credit per call.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="extractPdfPagesRequest"></param>
        /// <returns>ApiResponse of PdfToolsResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<PdfToolsResponse> ExtractPdfPagesWithHttpInfo(ExtractPdfPagesRequest extractPdfPagesRequest)
        {
            // verify the required parameter 'extractPdfPagesRequest' is set
            if (extractPdfPagesRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'extractPdfPagesRequest' when calling PDFToolsApi->ExtractPdfPages");

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = extractPdfPagesRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PdfToolsResponse>("/v1/pdf-tools/extract-pages", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ExtractPdfPages", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Extract pages from a PDF Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (&#x60;1-3&#x60;) and singles (&#x60;5&#x60;). Order is preserved: &#x60;5,1,3&#x60; outputs those 3 pages in that order.  **Credits:** 1 credit per call.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="extractPdfPagesRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PdfToolsResponse</returns>
        public async System.Threading.Tasks.Task<PdfToolsResponse> ExtractPdfPagesAsync(ExtractPdfPagesRequest extractPdfPagesRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<PdfToolsResponse> localVarResponse = await ExtractPdfPagesWithHttpInfoAsync(extractPdfPagesRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Extract pages from a PDF Return a single PDF containing only the selected pages of the input, in the order specified. Replaces the need for splitting + reassembling client-side.  **Pages syntax:** 1-indexed, comma-separated. Supports ranges (&#x60;1-3&#x60;) and singles (&#x60;5&#x60;). Order is preserved: &#x60;5,1,3&#x60; outputs those 3 pages in that order.  **Credits:** 1 credit per call.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="extractPdfPagesRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PdfToolsResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<PdfToolsResponse>> ExtractPdfPagesWithHttpInfoAsync(ExtractPdfPagesRequest extractPdfPagesRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'extractPdfPagesRequest' is set
            if (extractPdfPagesRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'extractPdfPagesRequest' when calling PDFToolsApi->ExtractPdfPages");


            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = extractPdfPagesRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<PdfToolsResponse>("/v1/pdf-tools/extract-pages", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ExtractPdfPages", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Merge PDFs Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mergePdfRequest"></param>
        /// <returns>PdfToolsResponse</returns>
        public PdfToolsResponse MergePdf(MergePdfRequest mergePdfRequest)
        {
            TemplateFox.SDK.Client.ApiResponse<PdfToolsResponse> localVarResponse = MergePdfWithHttpInfo(mergePdfRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Merge PDFs Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mergePdfRequest"></param>
        /// <returns>ApiResponse of PdfToolsResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<PdfToolsResponse> MergePdfWithHttpInfo(MergePdfRequest mergePdfRequest)
        {
            // verify the required parameter 'mergePdfRequest' is set
            if (mergePdfRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'mergePdfRequest' when calling PDFToolsApi->MergePdf");

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = mergePdfRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PdfToolsResponse>("/v1/pdf-tools/merge", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MergePdf", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Merge PDFs Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mergePdfRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PdfToolsResponse</returns>
        public async System.Threading.Tasks.Task<PdfToolsResponse> MergePdfAsync(MergePdfRequest mergePdfRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<PdfToolsResponse> localVarResponse = await MergePdfWithHttpInfoAsync(mergePdfRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Merge PDFs Concatenate 2 or more PDFs into a single PDF, in the order provided. Each input PDF is supplied as either an HTTPS URL or a base64 string.  **Credits:** 1 credit per call.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mergePdfRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PdfToolsResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<PdfToolsResponse>> MergePdfWithHttpInfoAsync(MergePdfRequest mergePdfRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'mergePdfRequest' is set
            if (mergePdfRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'mergePdfRequest' when calling PDFToolsApi->MergePdf");


            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = mergePdfRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<PdfToolsResponse>("/v1/pdf-tools/merge", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("MergePdf", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Rotate pages of a PDF Rotate every page by the same angle (&#x60;rotation&#x60;), or apply a per-page rotation map (&#x60;page_rotations&#x60;). Rotations are cumulative with the page&#39;s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rotatePdfRequest"></param>
        /// <returns>PdfToolsResponse</returns>
        public PdfToolsResponse RotatePdf(RotatePdfRequest rotatePdfRequest)
        {
            TemplateFox.SDK.Client.ApiResponse<PdfToolsResponse> localVarResponse = RotatePdfWithHttpInfo(rotatePdfRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Rotate pages of a PDF Rotate every page by the same angle (&#x60;rotation&#x60;), or apply a per-page rotation map (&#x60;page_rotations&#x60;). Rotations are cumulative with the page&#39;s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rotatePdfRequest"></param>
        /// <returns>ApiResponse of PdfToolsResponse</returns>
        public TemplateFox.SDK.Client.ApiResponse<PdfToolsResponse> RotatePdfWithHttpInfo(RotatePdfRequest rotatePdfRequest)
        {
            // verify the required parameter 'rotatePdfRequest' is set
            if (rotatePdfRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'rotatePdfRequest' when calling PDFToolsApi->RotatePdf");

            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = rotatePdfRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<PdfToolsResponse>("/v1/pdf-tools/rotate", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RotatePdf", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Rotate pages of a PDF Rotate every page by the same angle (&#x60;rotation&#x60;), or apply a per-page rotation map (&#x60;page_rotations&#x60;). Rotations are cumulative with the page&#39;s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rotatePdfRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PdfToolsResponse</returns>
        public async System.Threading.Tasks.Task<PdfToolsResponse> RotatePdfAsync(RotatePdfRequest rotatePdfRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            TemplateFox.SDK.Client.ApiResponse<PdfToolsResponse> localVarResponse = await RotatePdfWithHttpInfoAsync(rotatePdfRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Rotate pages of a PDF Rotate every page by the same angle (&#x60;rotation&#x60;), or apply a per-page rotation map (&#x60;page_rotations&#x60;). Rotations are cumulative with the page&#39;s existing rotation. Allowed angles: 0, 90, 180, 270.  **Credits:** 1 credit per call.
        /// </summary>
        /// <exception cref="TemplateFox.SDK.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="rotatePdfRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PdfToolsResponse)</returns>
        public async System.Threading.Tasks.Task<TemplateFox.SDK.Client.ApiResponse<PdfToolsResponse>> RotatePdfWithHttpInfoAsync(RotatePdfRequest rotatePdfRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'rotatePdfRequest' is set
            if (rotatePdfRequest == null)
                throw new TemplateFox.SDK.Client.ApiException(400, "Missing required parameter 'rotatePdfRequest' when calling PDFToolsApi->RotatePdf");


            TemplateFox.SDK.Client.RequestOptions localVarRequestOptions = new TemplateFox.SDK.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = TemplateFox.SDK.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = TemplateFox.SDK.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = rotatePdfRequest;

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<PdfToolsResponse>("/v1/pdf-tools/rotate", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RotatePdf", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
